<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Request a Quote Hyva Compatibility
 */

use Amasty\RequestQuote\Block\Cart\Sidebar;
use Amasty\RequestQuoteHyva\ViewModel\QuoteIcons;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var Sidebar $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$isLoggedIn = $block->isLoggedIn();
if (!$isLoggedIn) {
    return;
}

$quoteIcons = $viewModels->require(QuoteIcons::class);
?>

<a x-data="initAmQuoteIcon"
    @click.prevent.stop="toggleAmquoteEvent"
    @private-content-loaded.window="privateContentLoadedEvent"
    id="amquote-icon"
    href="<?= $escaper->escapeUrl($block->getQuoteCartUrl()) ?>"
    class="hidden relative inline-block">
    <span class="sr-only label">
        <?= $escaper->escapeHtml(__('Quote')) ?>
    </span>

    <svg class="w-5 md:w-6 h-5 md:h-6 text-white" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M6 2L3 6V20C3 20.5304 3.21071 21.0391 3.58579 21.4142C3.96086 21.7893 4.46957 22 5 22H19C19.5304 22 20.0391 21.7893 20.4142 21.4142C20.7893 21.0391 21 20.5304 21 20V6L18 2H6Z" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
        <path d="M3 6H21" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
        <path d="M16 10C16 11.0609 15.5786 12.0783 14.8284 12.8284C14.0783 13.5786 13.0609 14 12 14C10.9391 14 9.92172 13.5786 9.17157 12.8284C8.42143 12.0783 8 11.0609 8 10" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
    </svg>

    <span x-text="quotecartSummaryCount"
        class="absolute -top-2.5 -right-2.5 hidden h-5 px-2 py-1 text-xs font-semibold
                leading-none text-center text-white uppercase rounded-full 
                tabular-nums bg-primary"
        :class="summaryCountClass"></span>
</a>

<script>
    'use strict';

    (function() {
        document.addEventListener('DOMContentLoaded', function() {
            const quoteIcon = document.getElementById("amquote-icon");
            const insertBeforeNode = document.querySelector('<?= $escaper->escapeJs($block->getData('insertBeforeSelector')) ?>');
            if (!insertBeforeNode) {
                return;
            }

            const destination = insertBeforeNode.parentNode;
            destination.insertBefore(quoteIcon, insertBeforeNode);
            quoteIcon.classList.remove('hidden');
        });
    })()

    function initAmQuoteIcon() {
        return {
            quotecart: {},

            getData(data) {
                if (data.quotecart) {
                    this.quotecart = data.quotecart
                }
            },

            summaryCountClass() {
                return {
                    'hidden': !this.quotecart.summary_count,
                    'block': this.quotecart.summary_count
                }
            },

            toggleAmquoteEvent() {
                return this.$dispatch('toggle-amquote')
            },

            privateContentLoadedEvent(event) {
                return this.getData(this.$event.detail.data)
            },

            quotecartSummaryCount() {
                return this.quotecart.summary_count
            }
        }
    }

    window.addEventListener(
        'alpine:init',
        () => Alpine.data(
            'initAmQuoteIcon',
            initAmQuoteIcon
        ), {
            once: true
        }
    );
</script>
<?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>