<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\ViewModel\Checkout\AddressView\AddressListInterface;
use Hyva\Theme\Model\Modal\ModalBuilderInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Modal;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Api\Data\AddressInterface;
use Magento\Customer\Api\Data\AddressSearchResultsInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\Magewire\Checkout\AddressView\ShippingDetails\AddressList as Magewire;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Magewire $magewire */
/** @var AddressSearchResultsInterface $shippingAddressList */
/** @var AddressInterface $shippingAddress */
/** @var Escaper $escaper */
/** @var AddressListInterface $addressList */
/** @var ModalBuilderInterface $modal */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);


$addressList = $block->getData('address_list');
$addressListItems = $addressList->getAddressListItems();
$addressFormBlock = $block->getChildBlock('address-form');
$addressType = $addressList->getTypeNamespace();
?>
<div class="space-y-3 mb-6">
    <?= /* @noEscape */ $block->getChildBlock($addressList->getRendererTypeAlias($addressListItems))
        ->setData('address_list', $addressList)
        ->setData('active_entity', $magewire->activeAddressEntity)
        ->toHtml()
    ?>

    <?php if ($addressFormBlock): ?>
        <?php $modal = $viewModels->require(Modal::class)
            ->createModal()
            ->withDialogRefName($addressFormBlock->getNameInLayout())
            ->withContent($addressFormBlock->toHtml())
            ->addDialogClass('w-full max-w-4xl');
        ?>

        <div
            id="checkout-<?= $escaper->escapeHtmlAttr($addressType) ?>-address-dialog"
            x-data="mountainITTeakeaHyvaCheckoutAddressViewAddressList"
            x-on:address-form-modal-show.window="mountainITTeakeaHyvaCheckoutAddressViewAddressListAddressFormModalShowWindow215" data-hyvacsp1="<?= $escaper->escapeHtmlAttr($addressList->getTypeNamespace()) ?>" data-hyvacsp2="<?= /* @noEscape */ $addressList->getShowModalEvent() ?>"
            x-on:address-form-modal-hide.window="mountainITTeakeaHyvaCheckoutAddressViewAddressListAddressFormModalHideWindow216" data-hyvacsp3="<?= $escaper->escapeHtmlAttr($addressList->getTypeNamespace()) ?>" data-hyvacsp4="<?= /* @noEscape */ $addressList->getHideModalEvent() ?>"
            x-on:<?= /* @noEscape */ $addressList->getShowModalEvent() ?>.window="$el.dataset.hyvacsp5" data-hyvacsp5="<?= /* @noEscape */ $modal->getShowJs('#checkout-' . $addressType . '-address-button') ?>"
            x-on:<?= /* @noEscape */ $addressList->getHideModalEvent() ?>.window="hide()"
        >
            <?= /* @noEscape */ $modal ?>
        </div>

        <?php if ($addressList->canCreateAddresses()): ?>
            <div>
                <button
                    type="button"
                    id="checkout-<?= $escaper->escapeHtmlAttr($addressType) ?>-address-button"
                    wire:click="$emitTo('<?= /* @noEscape */ $addressList->getModalAddressFormBlockName() ?>', 'create')"
                    class="btn btn-flat gap-2 w-full justify-center bg-teakea-red hover:bg-teakea-red rounded-lg text-white"
                    aria-expanded="false"
                    aria-controls="checkout-<?= $escaper->escapeHtmlAttr($addressType) ?>-address-dialog"
                >
                    <?= $heroicons->plusHtml('', 18, 18, ['aria-hidden' => 'true']) ?>
                    <?= $escaper->escapeHtml(__('New Address')) ?>
                </button>
            </div>
        <?php endif ?>
    <?php endif ?>
</div>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function mountainITTeakeaHyvaCheckoutAddressViewAddressList() {
    return Object.assign(
        hyva.modal()
        ,{
            ['mountainITTeakeaHyvaCheckoutAddressViewAddressListAddressFormModalHideWindow216'](event) {if (this.$event.detail.type === `${this.$el.dataset.hyvacsp3}`) {
               this.$dispatch(`${this.$el.dataset.hyvacsp4}`)
            }},
            ['mountainITTeakeaHyvaCheckoutAddressViewAddressListAddressFormModalShowWindow215'](event) {if (this.$event.detail.type === `${this.$el.dataset.hyvacsp1}`) {
               this.$dispatch(`${this.$el.dataset.hyvacsp2}`)
            }},
        }
    )
}
window.addEventListener('alpine:init', () => Alpine.data('mountainITTeakeaHyvaCheckoutAddressViewAddressList', mountainITTeakeaHyvaCheckoutAddressViewAddressList), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>