<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\HeroiconsOutline;


/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$currentCategory = \Magento\Framework\App\ObjectManager::getInstance()
    ->get(\Magento\Framework\Registry::class)
    ->registry('current_category');
$catId = $currentCategory->getId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
$subcats = $subcategory->getChildrenCategories();

if (!$itemCount = count($subcats)) {
    return '';
}

?>
<script>
    'use strict';

    function initSliderComponent() {
        return {
            active: 0,
            itemCount: 0,
            getSlider() {
                return this.$root.querySelector('.js_slides');
            },
            pageSize: 4,
            pageFillers: 0,
            calcPageSize() {
                const slider = this.getSlider();
                if (slider) {
                    this.itemCount = slider.querySelectorAll('.js_slide').length;
                    this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                    ) - this.itemCount;
                }
            },
            calcActive() {
                const slider = this.getSlider();
                if (slider) {
                    const sliderItems = this.itemCount + this.pageFillers;
                    const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
                    this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                }
            },
            scrollPrevious() {
                this.scrollTo(this.active - this.pageSize);
            },
            scrollNext() {
                this.scrollTo(this.active + this.pageSize);
            },
            scrollTo(idx) {
                const slider = this.getSlider();
                if (slider) {
                    const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                    slider.scrollLeft = Math.floor(slideWidth) * idx;
                    this.active = idx;
                }
            }
        }
    }
</script>
<section
    class="w-full bg-techtic-cream py-[30px]"
    x-data="initSliderComponent()"
    x-init="calcPageSize();"
    @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })">
    <div class="relative ">
        <div class="flex justify-center pl-2.5 md:container !pr-0">
            <div class="relative w-full overflow-x-hidden max-w-screen-2xl ">
                <div class="relative flex flex-nowrap w-full overflow-auto js_slides snap gap-5"
                    @scroll.debounce="calcActive">
                    <?php foreach ($subcats as $subcat): ?>
                        <div class="single-slide flex shrink-0 js_slide min-h-[100px] max-h-[400px] min-w-[200px] w-[190px]">
                            <a class=" flex-col rounded-lg w-full font-normal text-center align-middle flex text-center text-ellipsis overflow-hidden" href="<?php echo $subcat->getUrl(); ?>">
                                <?php $sub_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
                                $subcat_url = $subcat->getUrl();
                                $categoryName = $subcat->getName();
                                // SEO text
                                $altTitle = $categoryName . ' - Techtic'; ?>
                                <img class="rounded-lg w-[190px] h-[150px] object-cover mx-auto"
                                    src="<?php echo $sub_category->getImageUrl() ?>"
                                    alt="<?= $escaper->escapeHtmlAttr($altTitle) ?>"
                                    title="<?= $escaper->escapeHtmlAttr($altTitle) ?>"
                                    height="300px" width="240px" loading="lazy">
                                <div class="font-normal text-base mx-auto break-word hyphens-auto pt-2">
                                    <?= $escaper->escapeHtml($categoryName) ?>
                                </div>
                            </a>
                        </div>
                    <?php endforeach; ?>

                </div>
            </div>
        </div>



        <!-- Pagination -->
        <div>
            <template x-if="itemCount > pageSize">
                <div class="flex items-center justify-between md:container absolute top-1/4 right-0 left-0 !px-0 w-full">
                    <button
                        aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                        tabindex="-1"
                        class="text-black rounded-full outline-none focus:outline-none flex-none lg:block z-10"
                        :class="{ 'opacity-[0] pointer-events-none' : active === 0 }"
                        @click="scrollPrevious">
                        <?= $heroicons->arrowNarrowLeftHtml("p-3 stroke-black h-[45px] sm:h-[50px] w-[45px] sm:w-[50px] lg:h-[45px] lg:w-[45px] rounded-full bg-white stroke-1", 24, 24) ?>
                    </button>

                    <button
                        aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                        tabindex="-1"
                        class=" text-black rounded-full outline-none focus:outline-none flex-none lg:block z-10"
                        :class="{ 'opacity-[0] pointer-events-none' : active >= itemCount-pageSize }"
                        @click="scrollNext">
                        <?= $heroicons->arrowNarrowRightHtml("p-3 stroke-black h-[45px] sm:h-[50px] w-[45px] sm:w-[50px] lg:h-[45px] lg:w-[45px] rounded-full bg-white stroke-1 ", 24, 24) ?>
                    </button>
                </div>
            </template>
        </div>
    </div>
</section>