<div class="full-bleed text-tertiary">
    <div class="max-w-[1488px] mx-auto mb-8">

        <div class="w-full h-[400px] md:h-[500px] flex items-center justify-center" >

            <img width="1488" height="500" fetchpriority="high" src="https://teakeam2.test/media/wysiwyg/teakea-home-1.jpg" alt="Kitchen" class="w-full h-full object-cover grayscale">

            <div class="absolute w-full h-[400px] md:h-[500px] flex flex-col items-center justify-center text-white p-16 2xl:p-8">
                <h1 class="text-4xl md:text-7xl font-bold mt-auto">Maatwerk</h1>
                <p class="text-center text-white text-3xl font-medium">Precies zoals jij het wilt!</p>
                <a href="#" class="btn mt-auto px-16 py-3 bg-primary hover:bg-tertiary text-white font-semibold text-base rounded-l-full rounded-tr-full shadow-md transition">
                    Ontdek Nu
                </a>
            </div>
        </div>
    </div>
</div>



