<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;

/** @var HyvaCsp $hyvaCsp */

?>
<script>
    function hyvaCheckoutCouponCode() {
        return hyva.createBooleanObject('visible', true, {
            couponCode: this.$wire.entangle('couponCode'),
            couponHits: this.$wire.entangle('couponHits'),

            rotateClass() {
                return {
                    'transform rotate-180': this.visible()
                }
            },
            inputHasCouponCodeClass() {
                return {
                    'has-coupon': this.couponCode,
                    'invalid': this.couponHits !== 0
                }
            }
        })
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('hyvaCheckoutCouponCode', hyvaCheckoutCouponCode)
    }, {
        once: true
    })
</script>
<?php $hyvaCsp->registerInlineScript() ?>