<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$segment = $block->getSegment();
$segmentTitle = $segment['title'];
$displayTitle = !empty($segmentTitle) ? $segmentTitle : (string) __('Discount');
?>
<div class="flex gap-4 justify-between items-center text-black border-b border-teakea-light-gray pb-2.5">
    <span class="label text-sm font-normal text-teakea-gray">
        <?= $escaper->escapeHtml($displayTitle) ?>
    </span>
    <span class="value flex w-fit flex-shrink-0 font-extrabold text-sm">
        <?= /* @noEscape */ $formatterViewModel->currency($segment['value'] ?? 0) ?>
    </span>
</div>
