<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$segment = $block->getSegment();

$shippingValue = $segment['value'] ?? 0;
$shipping = /* @noEscape */ $formatterViewModel->currency($shippingValue);
$freeShipping = $shippingValue <= 0;
?>
<div class="flex gap-4 justify-between pb-2.5 border-b border-hair items-center text-sm font-normal text-teak-muted">
    <span class="label">
        <?= $escaper->escapeHtml(array_key_exists('title', $segment)
            ? __($segment['title'])
            : __('Shipping')) ?>
    </span>
    <span class="<?= $freeShipping ? 'text-techtic-checkout-green' : 'text-teak-ink' ?> value font-mono">
        <?= $freeShipping ? "Gratis" : $shipping ?>
    </span>
</div>