<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */


// The item to render is set on the block before the template is rendered:
$column = $block->getData('item');

$buttonLabel = $column->getButton();
$buttonUrl = $column->getButtonUrl();
?>

<div>
    <a href="<?= $escaper->escapeUrl($column->getButtonUrl()) ?>"
       class="block w-full rounded-lg overflow-hidden"
    >
        <img src="<?= $escaper->escapeUrl($column->getThumbnail()); ?>"
             alt="<?= $escaper->escapeHtmlAttr($column->getTitle()) ?>"
             loading="lazy"
             class="object-cover hover:opacity-75 w-full min-h-14"
        >
    </a>
    <p class="mt-2 block text-base font-medium text-gray-900 truncate pointer-events-none">
        <?= $escaper->escapeHtml($column->getTitle()) ?>
    </p>
    <p class="mt-2 block text-sm font-medium text-gray-500 pointer-events-none">
        <?= /** @noEscape */ $column->getDescription(); ?>
    </p>
    <?php if ($buttonLabel && $buttonUrl): ?>
        <div class="mt-4 sm:flex">
            <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($buttonUrl)) ?>"
               class="inline-flex btn btn-primary">
                <?= $escaper->escapeHtml($buttonLabel) ?>
            </a>
        </div>
    <?php endif; ?>
</div>
