<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

// phpcs:disable Magento2.Templates.ThisInTemplate

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Cart\ItemOutput;
use Hyva\Theme\ViewModel\Modal;
use Magento\Checkout\Block\Cart\Grid;
use Magento\Checkout\ViewModel\Cart as CartViewModel;
use Magento\Framework\Escaper;

/** @var Grid $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var CartViewModel $cartViewModel */
$cartViewModel = $viewModels->require(CartViewModel::class);

/** @var Modal $modalViewModel */
$modalViewModel = $viewModels->require(Modal::class);

/** @var ItemOutput $cartItemOutputViewModel */
$cartItemOutputViewModel = $viewModels->require(ItemOutput::class);
?>
<?php $mergedCells = ($cartItemOutputViewModel->isItemPriceDisplayBoth() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
    x-data="{}"
    @submit.prevent="hyva.postCart($event.target)"
    method="post"
    id="form-validate"
    class="form form-cart w-full float-left">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart grid-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>

        <!-- Shopping Cart Items -->
        <div id="shopping-cart-items" class="cart items data grid w-full">
            <div class="cart-body flex flex-col gap-3">
                <?php foreach ($block->getItems() as $item): ?>
                    <div class="card-wrap p-4 sm:p-5 rounded-lg bg-white shadow-[0_1px_0_rgba(30,77,43,0.04),0_2px_8px_-2px_rgba(30,77,43,0.06)]">
                        <?= $block->getItemHtml($item) ?>
                    </div>
                <?php endforeach ?>
            </div>
        </div>

        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>