<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>



<div class="w-full flex flex-col mb-8 mt-3">
    <div class="flex flex-col-reverse lg:flex-row-reverse gap-x-5 gap-y-5">
        <div class="w-full lg:w-3/4 order-1 h-max">
            <?= $block->getChildHtml('form_before') ?>
            <?= $block->getChildHtml('cart-items') ?>
            <?= $block->getChildHtml('checkout_cart_widget') ?>
        </div>
        <div class="w-full lg:w-1/4">
            <div class="h-fit rounded-lg p-4 bg-white lg:sticky lg:top-20 shadow-[0_1px_0_rgba(30,77,43,0.04),0_2px_8px_-2px_rgba(30,77,43,0.06)]">
                <div class="flex flex-col pb-3 lg:pb-3 pt-3 lg:pt-0">
                    <h2 class="w-full text-lg xl:text-2xl font-medium title-font text-left font-garamond">
                        <?= $escaper->escapeHtml(__('Summary')) ?>
                    </h2>
                </div>
                <?= $block->getChildHtml('cart.discount') ?>
                <?= $block->getChildHtml('cart.summary') ?>
            </div>

            <?= $block->getLayout()
                ->createBlock(\Magento\Cms\Block\Block::class)
                ->setBlockId('trust_badges_cart')
                ->toHtml(); ?>

        </div>
    </div>
    <div class="w-full lg:w-3/4 lg:pr-8">

    </div>
</div>