<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<?php if ($block->hasData('title')): ?>
    <div class="section-title pb-4">
        <h2 class="font-garamond text-2xl font-normal text-teakea-neutral">
            <?= $escaper->escapeHtml($block->getData('title')) ?>
        </h2>
    </div>
<?php endif ?>
