<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Checkout\Magewire\Checkout\CouponCode as Magewire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Magewire $magewire */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$classCouponAvailability = $magewire->couponCode ? 'available' : 'not-available';
$saveAction = $magewire->couponCode ? 'revokeCouponCode' : 'applyCouponCode';
?>

<div
    x-data="hyvaCheckoutCouponCode" class="border py-3 px-3 rounded-lg">
    <button
        type="button"
        class="flex w-full items-center justify-between cursor-pointer gap-2 
                text-left text-sm text-teak-ink font-bold hover:text-teak-green font-garamond text-onSurface"
        aria-controls="checkout-coupon-code-details"
        x-on:click="toggleVisible"
        x-bind:aria-expanded="visible">
        <span class="flex items-center gap-2">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1.5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 0 0 3 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 0 0 5.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 0 0 9.568 3Z"></path>
            </svg>
            <?= $escaper->escapeHtml(__('Do you have a discount code?')) ?>
        </span>



        <span class="ml-auto"
            x-bind:class="rotateClass">
            <svg class="w-4 h-4 shrink-0 transition" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
            </svg>
        </span>
    </button>

    <div
        id="checkout-coupon-code-details"
        class="coupon-code <?= $escaper->escapeHtmlAttr($classCouponAvailability) ?> flex flex-col gap-2 mt-3 xl:flex-row"
        aria-label="<?= $escaper->escapeHtml(__('Do you have a discount code?')) ?>"
        x-show="visible"
        x-cloak>
        <label class="flex-1 xl:focus-within:relative border rounded-lg">
            <span class="sr-only"><?= $escaper->escapeHtml(__('Enter code')) ?></span>
            <input
                type="text"
                class="form-input w-full text-sm font-normal text-teak-muted py-2 px-4"
                placeholder="<?= $escaper->escapeHtmlAttr(__('Enter code')) ?>"
                wire:model.defer="couponCode"
                wire:loading.attr="disabled"
                wire:keydown.enter="<?= /* @noEscape */ $saveAction ?>"
                x-bind:class="inputHasCouponCodeClass"
                x-bind:disabled="couponCode">
        </label>
        <button
            type="button"
            class="text-teak-green bg-transparent border border-teak-green hover:text-white hover:bg-teak-green text-center text-sm w-28 items-center justify-center rounded-lg font-normal shadow-none py-2 px-4"
            x-bind:class="inputHasCouponCodeClass"
            wire:click="<?= /* @noEscape */ $saveAction ?>"
            wire:loading.attr="disabled">
            <span wire:loading.block class="hidden">
                <?= $escaper->escapeHtml(__('Apply')) ?>
            </span>
            <?php if ($magewire->couponCode): ?>
                <span aria-label="<?= $escaper->escapeHtml(__('Cancel Coupon')) ?>" wire:loading.remove>
                    <?= $escaper->escapeHtml(__('Cancel')) ?>
                </span>
            <?php else: ?>
                <span aria-label="<?= $escaper->escapeHtml(__('Apply Coupon')) ?>" wire:loading.remove>
                    <?= $escaper->escapeHtml(__('Apply')) ?>
                </span>
            <?php endif ?>
        </button>
    </div>
</div>