<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\ShippingSummary;
use Hyva\Checkout\ViewModel\Checkout\AddressRenderer;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var ShippingSummary $viewModel */

$viewModel = $viewModels->require(ShippingSummary::class);
$addressRenderer = $viewModels->require(AddressRenderer::class);

$address = $viewModel->getShippingAddress();
$carrier = $viewModel->getShippingCarrier();
?>
<div>
    <?php if ($address->getFirstname() || $address->getLastname()): ?>
        <div class="pb-4">
            <div class="section-title border-b border-slate-300 pb-1 mb-2.5">
                <h2 class="font-garamond text-2xl font-normal text-techtic-neutral">
                    <?= $escaper->escapeHtml((__('Ship To'))) ?>
                </h2>
            </div>

            <address class="text-sm font-normal text-techtic-gray">
                <?= /* @noEscape */ $addressRenderer->renderCustomerAddress($address) ?>
            </address>
        </div>
    <?php else: ?>
        <p>
            <?= $escaper->escapeHtml(__('No shipping address set.')) ?>
        </p>
    <?php endif ?>

    <?php if ($carrier): ?>
        <div>
            <div class="section-title border-b border-slate-300 pb-1 mb-2.5">
                <h2 class="font-garamond text-2xl font-normal text-techtic-neutral">
                    <?= $escaper->escapeHtml((__('Shipping Method'))) ?>
                </h2>
            </div>

            <p class="text-sm font-normal text-techtic-gray">
                <?= $escaper->escapeHtml($carrier) ?>
            </p>
        </div>
    <?php else: ?>
        <p>
            <?= $escaper->escapeHtml(__('No shipping method selected.')) ?>
        </p>
    <?php endif ?>
</div>