<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Search\Helper\Data as SearchHelper;
use Magento\Search\ViewModel\ConfigProvider as SearchConfig;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var SearchHelper $helper */
$helper = $this->helper(SearchHelper::class);

/** @var SearchConfig $searchConfig */
$searchConfig = $viewModels->require(SearchConfig::class);
?>
<script>
    'use strict';

    function initMiniSearch() {
        return {
            minSearchLength: <?= (int) $helper->getMinQueryLength() ?>,
            <?php if ($searchConfig->isSuggestionsAllowed()): ?>
                suggestions: [],
                suggest() {
                    const search = this.$refs.searchInput;
                    if (search.value.length >= this.minSearchLength) {
                        search.setCustomValidity('');
                        search.reportValidity();
                        this.fetchSuggestions(search.value);
                    } else {
                        this.suggestions = [];
                    }
                },
                fetchSuggestions(term) {
                    fetch(
                            window.BASE_URL + 'search/ajax/suggest?' + new URLSearchParams({
                                q: term
                            }), {
                                headers: {
                                    'X-Requested-With': 'XMLHttpRequest'
                                }
                            }
                        )
                        .then(response => response.json())
                        .then(result => this.suggestions = result);
                },
            <?php endif ?>
            search(term) {
                const search = this.$refs.searchInput;
                term = term || search.value;
                if (term.length < this.minSearchLength) {
                    search.setCustomValidity('<?= $escaper->escapeJs(
                                                    __('Minimum Search query length is %1', $helper->getMinQueryLength())
                                                ) ?>');
                    search.reportValidity();
                } else {
                    search.setCustomValidity('');
                    search.value = term;
                    this.$refs.form.submit();
                }
            },
            focusElement(element) {
                if (element && element.nodeName === "DIV") {
                    element.focus();
                    return true;
                } else {
                    return false;
                }
            }
        }
    }
</script>

<?php $mobileMenuClass = (string) $block->getData('mobile_menu_class'); ?>

<div class="container py-2.5 !px-6 mx-auto text-black<?= $escaper->escapeHtmlAttr($mobileMenuClass) ?>" x-data="initMiniSearch()">
    <form class="form minisearch flex gap-2.5" id="search_mini_form" x-ref="form" @submit.prevent="search()"
        action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get" role="search">
        <label class="hidden" for="search" data-role="minisearch-label">
            <span><?= $escaper->escapeHtml(__('Search')) ?></span>
        </label>
        <input id="search"
            x-ref="searchInput"
            type="search"
            autocomplete="off"
            name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
            value="<?=
                    /** @noEscape */
                    $helper->getEscapedQueryText() ?>"
            placeholder="<?= $escaper->escapeHtmlAttr(__('Search...')) ?>"
            maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
            class="w-full p-0 text-sm border-0 <?= $escaper->escapeHtmlAttr($mobileMenuClass ? 'text-teak-muted bg-white placeholder:text-teak-muted' : 'text-white bg-[#282828] placeholder:text-white') ?>"
            @search-open.window.debounce.10="
                    $el.focus()
                    $el.select()
               "
            <?php if ($searchConfig->isSuggestionsAllowed()): ?>
            @focus.once="suggest"
            @input.debounce.300="suggest"
            @keydown.arrow-down.prevent="focusElement($root.querySelector('[tabindex]'))"
            <?php endif ?> />
        <button type="submit"
            title="<?= $escaper->escapeHtml(__('Search')) ?>"
            class="action search"
            aria-label="Search">
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M13.8938 13.8676L17.5 17.5M15.8333 9.16667C15.8333 12.8486 12.8486 15.8333 9.16667 15.8333C5.48477 15.8333 2.5 12.8486 2.5 9.16667C2.5 5.48477 5.48477 2.5 9.16667 2.5C12.8486 2.5 15.8333 5.48477 15.8333 9.16667Z" stroke="<?= $escaper->escapeHtmlAttr($mobileMenuClass ? '#6B6B6B' : 'white') ?>" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
        </button>
        <?php if ($searchConfig->isSuggestionsAllowed()): ?>
            <template x-if="suggestions.length > 0">
                <div class="w-full leading-normal transition appearance-none text-grey-800 flex flex-col mt-1">
                    <template x-for="suggestion in suggestions">
                        <div class="flex justify-between p-2 bg-container-lighter even:bg-container mb-1 cursor-pointer
                                border border-container hover:bg-container-darker"
                            tabindex="0"
                            @click="search(suggestion.title)"
                            @keydown.enter="search(suggestion.title)"
                            @keydown.arrow-up.prevent="
                            focusElement($event.target.previousElementSibling) || $refs.searchInput.focus()
                        "
                            @keydown.arrow-down.prevent="focusElement($event.target.nextElementSibling)">
                            <span x-text="suggestion.title"></span>
                            <span x-text="suggestion.num_results"></span>
                        </div>
                    </template>
                </div>
            </template>
        <?php endif ?>
    </form>
</div>