<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Title;

/** @var Escaper $escaper */
/** @var Title $block */

$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : 'text-3xl';
$titleHtml = '';
if (trim((string)$block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $escaper->escapeHtml($block->getPageHeading())
        . '</span>';
}

?>
<?php if ($titleHtml): ?>
    <div class="container mt-0 mb-2.5 flex flex-col title-page !px-0">
        <h1 class="text-xl lg:text-3xl font-normal text-techtic-neutral-dark md:order-2 leading-snug line-clamp-2 font-garamond"
            <?php if ($block->getId()): ?> id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>>
            <?= /* @noEscape */ $titleHtml ?>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>