<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Magewire\Checkout\TermsConditions;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var Template $block */
/** @var TermsConditions $magewire */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$availableTerms = $block->getData('terms');
?>
<?php if (is_array($availableTerms) && count($availableTerms) !== 0): ?>
<div class="space-y-4">
    <?php foreach ($availableTerms as $agreement): ?>
        <div x-data="mountainITTeakeaHyvaCheckoutTermsConditionsList"
             x-on:terms-conditions:details:error.window="mountainITTeakeaHyvaCheckoutTermsConditionsListErrorWindow233" data-hyvacsp1="<?= $escaper->escapeHtmlAttr($agreement->getAgreementId()) ?>"
        >
            <div class="flex gap-x-2 md:gap-x-4">
                <div class="flex items-center">
                    <input type="checkbox"
                           class="h-4 w-4 rounded"
                           id="agreement_<?= $escaper->escapeHtmlAttr($agreement->getAgreementId()) ?>"
                           value="<?= $escaper->escapeHtmlAttr($agreement->getMode()) ?>"
                           wire:model="termAcceptance.<?= $escaper->escapeHtmlAttr($agreement->getAgreementId()) ?>"
                            wire:loading.attr="disabled"
                           required
                           x-on:input="mountainITTeakeaHyvaCheckoutTermsConditionsListInput234"
                    />
                </div>

                <div class="flex">
                    <div class="flex justify-between items-center gap-x-4">
                        <label
                            for="agreement_<?= $escaper->escapeHtmlAttr($agreement->getAgreementId()) ?>"
                            class="flex flex-wrap mb-0 text-base font-normal text-teakea-neutral font-garamond cursor-pointer w-fit gap-x-1"
                        >
                            <?= $escaper->escapeHtml(__('Yes, I agree to the')) ?>
                            <button
                                type="button"
                                class="inline whitespace-normal text-primary underline underline-offset-2 font-medium"
                                title="<?= $escaper->escapeHtmlAttr(__('Read Details')) ?>"
                                x-on:click.prevent="mountainITTeakeaHyvaCheckoutTermsConditionsListClickPrevent236"
                                data-hyvacsp2="<?= $escaper->escapeHtmlAttr($agreement->getAgreementId()) ?>"
                            >
                                <?= $escaper->escapeHtml(__('terms and conditions')) ?>
                                <span class="sr-only"><?= $escaper->escapeHtml(__('Read Details')) ?></span>
                            </button>
                        </label>
                    </div>
                </div>
            </div>

            <div class="backdrop z-30"
                 @term-dialog:open.window="mountainITTeakeaHyvaCheckoutTermsConditionsListOpenWindow237" data-hyvacsp3="<?= $escaper->escapeHtmlAttr($agreement->getAgreementId()) ?>"
                 x-transition:enter="ease-in-out duration-500"
                 x-transition:enter-start="opacity-0"
                 x-transition:enter-end="opacity-100"
                 x-transition:leave="ease-in-out duration-500"
                 x-transition:leave-start="opacity-100"
                 x-transition:leave-end="opacity-0"
                 x-on:click="mountainITTeakeaHyvaCheckoutTermsConditionsListClick238"
                 x-show="open"
                 x-cloak></div>

            <div role="dialog"
                 aria-modal="true"
                 x-on:click.outside.away="mountainITTeakeaHyvaCheckoutTermsConditionsListClickOutsideAway239"
                 x-show="open"
                 class="fixed inset-y-0 right-0 z-30 flex max-w-full"
                 x-cloak
            >
                <div class="relative w-screen max-w-md shadow-2xl pb-6 bg-white overflow-auto"
                     @term-dialog:open.window="mountainITTeakeaHyvaCheckoutTermsConditionsListOpenWindow240" data-hyvacsp4="<?= $escaper->escapeHtmlAttr($agreement->getAgreementId()) ?>"
                     x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
                     x-transition:enter-start="translate-x-full"
                     x-transition:enter-end="translate-x-0"
                     x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
                     x-transition:leave-start="translate-x-0"
                     x-transition:leave-end="translate-x-full"
                     x-show="open"
                     x-cloak
                >
                    <div class="flex flex-col p-6 space-y-6">
                        <h2 class="text-gray-800 text-xl font-medium">
                            <?php if ($agreement->getIsHtml()): ?>
                                <?= /** @noEscape */ $agreement->getCheckboxText(); ?>
                            <?php else: ?>
                                <?= $escaper->escapeHtml($agreement->getCheckboxText()) ?>
                            <?php endif; ?>
                        </h2>

                        <?php if ($agreement->getIsHtml()): ?>
                            <?= /* @noEscape */ $agreement->getContent() ?>
                        <?php else: ?>
                            <p>
                                <?= $escaper->escapeHtml($agreement->getContent()) ?>
                            </p>
                        <?php endif ?>

                        <div class="flex justify-between">
                            <button type="button"
                                    wire:click="$set('termAcceptance.<?= $escaper->escapeHtmlAttr($agreement->getAgreementId()) ?>', true)"
                                    x-on:click="mountainITTeakeaHyvaCheckoutTermsConditionsListClick238"
                                    class="btn btn-primary"
                            >
                                <?= $escaper->escapeHtml(__('Accept Terms')) ?>
                            </button>

                            <button type="button"
                                    wire:click="$set('termAcceptance.<?= $escaper->escapeHtmlAttr($agreement->getAgreementId()) ?>', false)"
                                    x-on:click="mountainITTeakeaHyvaCheckoutTermsConditionsListClick238"
                                    class="btn btn-secondary"
                            >
                                <?= $escaper->escapeHtml(__('Deny Terms')) ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>
<?php endif ?>

