<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Helper\Address as AddressHelper;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Gender $block */

?>
<div class="field field-reserved gender<?= $block->isRequired() ? ' required' : '' ?>">
    <label class="label block text-sm font-semibold text-teak-ink mb-1.5" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('gender')) ?>">
        <span><?= $escaper->escapeHtml($block->getStoreLabel('gender')) ?></span>
    </label>
    <div class="control">
        <select id="<?= $escaper->escapeHtmlAttr($block->getFieldId('gender')) ?>"
            name="<?= $escaper->escapeHtmlAttr($block->getFieldName('gender')) ?>"
            title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('gender')) ?>"
            class="form-select w-full border border-techtic-light-gray rounded-lg px-4 
                    py-3 text-sm placeholder-gray-400 focus:outline-none 
                    focus:ring-2 focus:ring-[#163A20]/30 focus:border-[#163A20]"
            <?php if ($block->isRequired()): ?>required<?php endif; ?>>
            <?php $options = $block->getGenderOptions(); ?>
            <?php $value = $block->getGender(); ?>
            <?php foreach ($options as $option): ?>
                <option value="<?= $escaper->escapeHtmlAttr($option->getValue()) ?>"
                    <?= ($option->getValue() == $value) ? 'selected="selected"' : '' ?>><?= $escaper->escapeHtml(__($option->getLabel())) ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>