<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<?php if ($childrenHtml = $block->getChildHtml()): ?>
    <div class="flex 1/4 hidden">
        <?= /** @noEscape */ $childrenHtml ?>
    </div>
<?php endif; ?>
