<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Cms\Block\BlockByIdentifier as CmsBlock;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$uniqueId = '_' . uniqid();
$maxLevel = $block->getmaxLevel() ?: 3;
$canOpenOnHover = false; // DISABLED HOVER
$topMenuCtaItem = $block->getTopMenuCtaItem();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menu = $viewModelNavigation->getNavigation(2 + $maxLevel);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());
?>

<nav
    class="navigation hidden lg:block grow"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
    x-data="initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()"
    x-ref="nav-desktop"
    @load.window="setActiveMenu($root)">
    <ul class="flex flex-wrap gap-x-8 items-center">
        <li class="flex items-center" role="none">
            <a role="menuitem" class="flex w-full level-0 text-neutral-950 font-medium text-sm not-italic leading-4"
                href="<?php echo $block->getUrl(''); ?>"><?php echo __('Home'); ?></a>
        </li>
        <?php foreach ($menu as $item): ?>
            <?php if (!empty($item['childData'])): ?>
                <li
                    class="level-0"
                    x-data="{ open: false }"
                    @click.outside="open = false"
                    @keydown.escape="open = false">
                    <?php
                    $menuId = 'desktop-menu-' . str_replace('-node', '', $item['id']);
                    $cmsBlockHtml = $this->getLayout()
                        ->createBlock(CmsBlock::class)
                        ->setIdentifier($menuId)
                        ->toHtml();
                    ?>
                    <button
                        type="button"
                        class="level-0 group w-full flex justify-between items-center gap-1 text-neutral-950 font-medium text-sm not-italic leading-4"
                        @click="open = !open
                        if (open) {
                            const firstLevel1 = $el.nextElementSibling.querySelector('.level-1 a, .level-1 button');
                            if (firstLevel1) { firstLevel1.click(); }
                        }"
                        aria-expanded="false"
                        :aria-expanded="open"
                        aria-controls="<?= $escaper->escapeHtml($menuId) ?>">
                        <?= $escaper->escapeHtml($item['name']) ?>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                            :class="{ 'rotate-180': open }"
                            class="transition-transform duration-200">
                            <path d="M6 9L12 15L18 9" stroke="black" stroke-linecap="round" stroke-linejoin="round" />
                        </svg>
                    </button>
                    <div
                        id="<?= $escaper->escapeHtml($menuId) ?>"
                        class="z-30 absolute top-[50px] inset-x-0 border-t border-slate-100 rounded-b-md bg-teakea-cream shadow-md
                            overflow-hidden <?= !empty($cmsBlockHtml) ? "grid grid-cols-[minmax(0px,1fr)_theme('spacing.72')]" : '' ?>"
                        x-show="open === true"
                        x-transition
                        x-cloak>
                        <div class="relative overflow-auto">
                            <ul class="flex flex-col pb-2.5 w-72 bg-teakea-lighter-yellow">

                                <?php foreach ($item['childData'] as $subMenu): ?>
                                    <?= $block->getLayout()->getBlock('topmenu_desktop_item')
                                        ->setItem($subMenu)
                                        ->setLevel(1)
                                        ->toHtml() ?>
                                <?php endforeach; ?>
                                <li class="text-center py-3.5 px-8 border-t border-[#00000033]">
                                    <a
                                        href="<?= $escaper->escapeUrl($item['url']) ?>"
                                        class="flex py-3 px-2 text-center justify-center uppercase aria-[current=page]:font-semibold border border-black font-semibold text-sm text-[#1e1e1e]"><?= $escaper->escapeHtml(__('See all %1', $item['name'])) ?></a>
                                </li>
                            </ul>
                        </div>
                        <?php if (!empty($cmsBlockHtml)): ?>
                            <div><?=
                                    /** @noEscape */
                                    $cmsBlockHtml ?></div>
                        <?php endif; ?>
                    </div>
                </li>
            <?php else: ?>
                <li>
                    <a
                        href="<?= $escaper->escapeUrl($item['url']) ?>"
                        title="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
                        class="level-0 flex text-neutral-950 font-medium text-sm not-italic leading-4
                            <?= $item['name'] === $topMenuCtaItem ? 'text-red-700' : '' ?>">
                        <?= $escaper->escapeHtml($item['name']) ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php
        echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('nav-items-teakea')
            ->toHtml();
        ?>
    </ul>
</nav>
<script>
    const initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        const maxLevel = <?= $maxLevel ?>;

        return {
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a'))
                    .filter(link => link.href === window.location.href.split('?')[0])
                    .forEach(item => {
                        item.setAttribute('aria-current', 'page');

                        for (let level = 0; level < maxLevel; level++) {
                            const closestMenu = item.closest(`.level-${level}`);

                            if (closestMenu) {
                                const button = closestMenu.querySelector('button');
                                if (button) {
                                    button.setAttribute('data-has-current', '');
                                }
                            }
                        }
                    });
            }
        }
    }
</script>