<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Cms\Block\BlockByIdentifier as CmsBlock;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$uniqueId = '_' . uniqid();
$canOpenOnHover = $block->getOpenTopLevelMenuOnHover();
$showTopLevelAllLink = $block->getShowTopLevelAllLink() !== null ? $block->getShowTopLevelAllLink() : true;
$topMenuCtaItem = $block->getTopMenuCtaItem();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menu = $viewModelNavigation->getNavigation(5);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());
?>

<nav
    class="navigation hidden lg:block"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
    x-data="initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()"
    x-ref="nav-desktop"
    @load.window="setActiveMenu($root)">
    <ul class="flex flex-wrap gap-x-8">
        <?php foreach ($menu as $item): ?>
            <?php if (!empty($item['childData'])): ?>
                <li
                    class="level-0"
                    x-data="{
                        open: false,
                        canHover(func) {
                            const isHoverableDevice = window.matchMedia('(hover: hover) and (pointer: fine)').matches;
                            if (!isHoverableDevice) return;
                            func();
                        }
                    }"
                    @click.outside="open = false"
                    <?php if ($canOpenOnHover): ?>
                    @mouseenter="canHover(() => { open = true })"
                    @mouseleave="canHover(() => { open = false })"
                    <?php endif ?>
                    @keydown.escape="open = false">
                    <?php $menuId = 'desktop-menu-' . str_replace('-node', '', $item['id']) ?>
                    <button
                        type="button"
                        class="text-white level-0 group w-full flex justify-between items-center gap-1
                            transition py-6 text-neutral-950 font-medium text-sm not-italic leading-4
                            aria-expanded:text-teakea-terracotta data-[has-current]:aria-expanded:text-teakea-terracotta
                            data-[has-current]:hover:text-teakea-terracotta"
                        @click="open = !open"
                        aria-expanded="false"
                        :aria-expanded="open"
                        aria-controls="<?= $escaper->escapeHtml($menuId) ?>">
                        <?= $escaper->escapeHtml($item['name']) ?>
                        <!-- Arrow only toggles submenu -->
                        <span
                            class="cursor-pointer"
                            @click.stop.prevent="open = !open"
                            role="button"
                            aria-label="Toggle submenu">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                                :class="{ 'rotate-180 transition': open }"
                                class="transition-transform duration-200">
                                <path d="M6 9L12 15L18 9" stroke="white" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </span>
                    </button>
                    <div
                        id="<?= $escaper->escapeHtml($menuId) ?>"
                        class="z-30 absolute inset-x-0 flex gap-8 container py-6 min-h-64 border-t border-slate-100 rounded-b-lg shadow-md overflow-auto bg-teakea-cream pl-12 w-full"
                        x-show="open === true"
                        x-transition
                        x-cloak>
                        <div class="grow flex flex-col justify-between">
                            <ul class="grid grid-cols-<?= $escaper->escapeHtml(count($item['childData'])) ?> gap-8 border-b border-[#00000033]">
                                <?php foreach ($item['childData'] as $subMenu): ?>
                                    <li class="break-inside-avoid pb-4">
                                        <a
                                            href="<?= $escaper->escapeUrl($subMenu['url']) ?>"
                                            class="level-1 block text-lg text-black font-bold mb-2.5 hover:underline aria-[current=page]:underline"><?= $escaper->escapeHtml($subMenu['name']) ?></a>
                                        <?php if (!empty($subMenu['childData'])): ?>
                                            <ul class="list-disc pl-5">
                                                <?php foreach ($subMenu['childData'] as $subMenuItems): ?>
                                                    <li>
                                                        <a
                                                            href="<?= $escaper->escapeUrl($subMenuItems['url']) ?>"
                                                            class="level-2 block py-1 hover:underline aria-[current=page]:underline"><?= $escaper->escapeHtml($subMenuItems['name']) ?></a>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                            <?php if ($showTopLevelAllLink): ?>
                                <div class="mt-4 py-3.5">
                                    <a
                                        href="<?= $escaper->escapeUrl($item['url']) ?>"
                                        class="level-0 inline py-3 px-2 text-center justify-center uppercase aria-[current=page]:font-semibold border border-black font-semibold text-sm text-[#1e1e1e] hover:underline aria-[current=page]:underline"><?= $escaper->escapeHtml(__('See all %1', $item['name'])) ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                        <?php
                        $cmsBlockHtml = $this->getLayout()
                            ->createBlock(CmsBlock::class)
                            ->setIdentifier($menuId)
                            ->toHtml();
                        if (!empty($cmsBlockHtml)):
                        ?>
                            <div class="max-w-[50%] hidden">
                                <?=
                                /** @noEscape */
                                $cmsBlockHtml ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </li>
            <?php else: ?>
                <li>
                    <a
                        href="<?= $escaper->escapeUrl($item['url']) ?>"
                        title="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
                        class="text-white level-0 w-full flex justify-between items-center
                                transition py-7 text-neutral-950 font-medium text-sm not-italic leading-4
                                data-[has-current]:text-teakea-terracotta
                            data-[has-current]:hover:text-teakea-terracotta
                            <?= $item['name'] === $topMenuCtaItem ? 'text-neutral-950' : '' ?>">
                        <?= $escaper->escapeHtml($item['name']) ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</nav>
<script>
    const initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a'))
                    .filter(link => link.href === window.location.href.split('?')[0])
                    .forEach(item => {
                        item.setAttribute('aria-current', 'page');

                        for (let level = 0; level < 3; level++) {
                            const closestMenu = item.closest(`.level-${level}`);

                            if (closestMenu) {
                                const button = closestMenu.querySelector('button');
                                if (button) {
                                    button.setAttribute('data-has-current', '');
                                }
                            }
                        }
                    });
            }
        }
    }
</script>