<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Cms\Block\Block;
use Magento\Framework\View\Element\Template;

/** @var Template $block */

$navHtmlLeft = $block->getChildHtml('hyva.checkout.navigation.left');
$navHtmlRight = $block->getChildHtml('hyva.checkout.navigation.right');
?>
<nav x-data="mountainITTeakeaHyvaNavigation"
     class="nav-main

            text-center
            flex flex-col-reverse md:flex-row
            gap-y-2 md:gap-y-0 md:gap-x-0
            !mb-2"
>
    <?php if (! empty($navHtmlLeft)): ?>
    <div class="flex flex-col-reverse md:flex-row
                gap-y-2 md:gap-x-2
                w-full
                md:items-center
                bg-gray-50
                p-2
                rounded-lg md:rounded-r-none"
    >
        <?= /* @noEscape */ $navHtmlLeft ?>
    </div>
    <?php endif ?>

    <div class="flex flex-col-reverse md:flex-col
                gap-y-2 md:gap-x-2
                w-full
                justify-end
                md:items-center"
    >
        <?= /* @noEscape */ $navHtmlRight ?>

        <?php
        echo $block->getLayout()
                ->createBlock(Block::class)
                ->setBlockId('checkout-badges-desktop')
                ->toHtml();
        ?>
    </div>
</nav>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function mountainITTeakeaHyvaNavigation() {
    return Object.assign(
        initCheckoutNavigation()
    )
}
window.addEventListener('alpine:init', () => Alpine.data('mountainITTeakeaHyvaNavigation', mountainITTeakeaHyvaNavigation), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>