<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */
/** @var StoreConfig $storeConfig */
$heroicons = $viewModels->require(HeroiconsOutline::class);
$storeConfig = $viewModels->require(StoreConfig::class);

$defaultSuccessMessageTimeout = $storeConfig->getStoreConfig('hyva_theme_general/messages/success_message_timeout');

?>
<script>
    <?php if ($defaultSuccessMessageTimeout): ?>
        window.defaultSuccessMessageTimeout = <?= (int) $defaultSuccessMessageTimeout ?>;
    <?php endif; ?>

    function initMessages() {
        "use strict";
        return {
            messages: window.mageMessages || [],
            isEmpty() {
                return this.messages.reduce(
                    function(isEmpty, message) {
                        return isEmpty && message === undefined
                    }, true
                )
            },
            removeMessage(messageIndex) {
                this.messages[messageIndex] = undefined;
            },
            addMessages(messages, hideAfter) {
                messages.map((message) => {
                    this.messages = this.messages.concat(message);
                    if (hideAfter === undefined && message.type === 'success' && window.defaultSuccessMessageTimeout) {
                        hideAfter = window.defaultSuccessMessageTimeout;
                    }
                    if (hideAfter) {
                        this.setHideTimeOut(this.messages.length - 1, hideAfter);
                    }
                });
            },
            setHideTimeOut(messageIndex, hideAfter) {
                setTimeout((messageIndex) => {
                    this.removeMessage(messageIndex);
                }, hideAfter, messageIndex);
            },
            eventListeners: {
                ['@messages-loaded.window'](event) {
                    this.addMessages(event.detail.messages, event.detail.hideAfter)
                },
                ['@private-content-loaded.window'](event) {
                    const data = event.detail.data;
                    if (
                        data.messages &&
                        data.messages.messages &&
                        data.messages.messages.length
                    ) {
                        this.addMessages(data.messages.messages);
                    }
                },
                ['@clear-messages.window']() {
                    this.messages = [];
                }
            }
        }
    }
</script>
<?php $hyvaCsp->registerInlineScript() ?>
<section id="messages"
    x-data="mountainITHyvaChildHyvaMessages"
    x-bind="eventListeners"
    aria-live="assertive"
    role="alert">
    <template x-if="mountainITHyvaChildHyvaMessagesIf748">
        <div class="w-full">
            <div class="messages px-2.5 md:px-6 mx-auto py-3 container">
                <template x-for="(message, index) in messages" :key="index">
                    <div>
                        <template x-if="message">
                            <div class="message" :class="mountainITHyvaChildHyvaMessagesClass749"
                                :ui-id="mountainITHyvaChildHyvaMessagesUiId750">
                                <span x-html="mountainITHyvaChildHyvaMessagesHtml751"></span>
                                <button
                                    type="button"
                                    class="text-gray-600 hover:text-black"
                                    aria-label="<?= $escaper->escapeHtml(__('Close message')) ?>"
                                    @click.prevent="mountainITHyvaChildHyvaMessagesClickPrevent752">
                                    <?= $heroicons->xHtml('stroke-current', 18, 18, ['aria-hidden' => 'true']); ?>
                                </button>
                            </div>
                        </template>
                    </div>
                </template>
            </div>
        </div>
    </template>
</section>
<script>
    <?php /** Generated with hyva-csp-helper.php */ ?>

    function mountainITHyvaChildHyvaMessages() {
        return Object.assign(
            initMessages(), {
                ['mountainITHyvaChildHyvaMessagesClass749']() {
                    return this.message.type
                },
                ['mountainITHyvaChildHyvaMessagesClickPrevent752'](event) {
                    return this.removeMessage(this.index)
                },
                ['mountainITHyvaChildHyvaMessagesHtml751']() {
                    return this.message.text
                },
                ['mountainITHyvaChildHyvaMessagesIf748']() {
                    return !this.isEmpty()
                },
                ['mountainITHyvaChildHyvaMessagesUiId750']() {
                    return 'message-' + this.message.type
                },
            }
        )
    }
    window.addEventListener('alpine:init', () => Alpine.data('mountainITHyvaChildHyvaMessages', mountainITHyvaChildHyvaMessages), {
        once: true
    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>