<?php

declare(strict_types=1);


/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */



use Hyva\Checkout\Magewire\Checkout\PriceSummary\CartItems;
use Hyva\Checkout\ViewModel\Checkout\PriceSummary\CartItems as CartItemsViewModel;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Tax\Helper\Data as TaxHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var CartItems $magewire */
/** @var CartItemsViewModel $cartItemsViewModel */
/** @var TaxHelper $taxHelper */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$cartItemsViewModel = $viewModels->require(CartItemsViewModel::class);
$taxHelper = $this->helper(TaxHelper::class);

$quoteItems = $magewire->getQuoteItemData();
$quoteItemsCount = $quoteItems ? count($quoteItems) : 0;
?>

<div x-data="TechticHyvaChildHyvaCheckoutPriceSummaryCartItems" x-bind:open="expand" class=" border border-techtic-light-gray mb-5 rounded-lg">
    <button
        type="button"
        class="group w-full flex items-center justify-between cursor-pointer py-3 px-3"
        aria-controls="checkout-cart-details"
        x-on:click="TechticHyvaChildHyvaCheckoutPriceSummaryCartItemsClick231"
        x-bind:aria-expanded="expand"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Cart') . ' ' . ($quoteItemsCount > 1
                        ? __('%1 Items', $quoteItemsCount)
                        : __('%1 Item', $quoteItemsCount))) ?>">
        <span class="w-fit flex flex-row gap-x-4 items-center">
            <span class="relative">

                <?= $heroicons->shoppingCartHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
                <span class="absolute top-0 left-4 h-4 w-4 py-1 -mt-3 -mr-3 text-xs font-bold text-center text-white leading-none
                    rounded-full block transform -translate-x-1 translate-y-1 text-[10px] bg-techtic-red"
                    aria-hidden="true">
                    <?= /* @noEscape */
                    $quoteItemsCount ?>
                </span>
            </span>

            <span class="h-fit text-techtic-neutral font-bold text-sm font-garamond">
                <?= $escaper->escapeHtml(__('Your Order')) ?>
            </span>
        </span>

        <span class="transform transition duration-300" :class="TechticHyvaChildHyvaCheckoutPriceSummaryCartItemsClass232">
            <?= $heroicons->chevronDownHtml('', 16, 16, ['aria-hidden' => 'true']) ?>
        </span>

    </button>

    <div
        id="checkout-cart-details"
        class="cart-items"
        x-show="expand"
        x-cloak>
        <div class="flex flex-col h-full space-y-6">
            <div class="relative grid">
                <?php if ($quoteItems): ?>
                    <?php foreach ($quoteItems as $item): ?>
                        <div class="flex flex-row gap-2 border-b last:border-b-0 border-[#D8D8D8] p-2">
                            <div class="flex relative">
                                <img src="<?= $escaper->escapeUrl($item['thumbnail']) ?>"
                                    width="75"
                                    height="75"
                                    alt="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
                                    loading="lazy"
                                    class="rounded-lg max-w-16 max-h-16 w-16 h-16" />

                                <span class="h-5 w-5 py-1
                                                text-xs text-center text-white
                                                leading-none font-bold
                                                rounded-full
                                                bg-techtic-red
                                                block absolute
                                                top-16 left-1/2 transform -translate-x-1/2 -translate-y-1/2
                                                shadow-md
                                                ring-4 ring-white">
                                    <?= /* @noEscape */ $item['qty'] ?>
                                </span>
                            </div>

                            <div class="flex flex-col space-y-2">
                                <div class="flex gap-2 justify-between flex-col">
                                    <div class="product-title">
                                        <p class="text-base text-teak-ink line-clamp-2 font-medium leading-tight hover:text-teak-green">
                                            <?= $escaper->escapeHtml($item['name']) ?>
                                        </p>

                                        <p class="text-sm text-teak-muted pt-2">
                                            <span class="sr-only"><?= $escaper->escapeHtml(__('Sku')) ?>:</span>
                                            <?= $escaper->escapeHtml($item['sku']) ?>
                                        </p>
                                    </div>

                                    <div class="product-price text-right text-lg text-teak-ink leading-none font-garamond">
                                        <?php if ($taxHelper->displayCartPriceInclTax() || $taxHelper->displayCartBothPrices()): ?>
                                            <span class="price-including-tax" data-label="<?= $escaper->escapeHtmlAttr(__('Incl. Tax')) ?>">
                                                <?= /* @noEscape */ $formatterViewModel->currency($item['row_total_incl_tax']) ?>
                                            </span>
                                        <?php endif ?>

                                        <?php if ($taxHelper->displayCartPriceExclTax() || $taxHelper->displayCartBothPrices()): ?>
                                            <span class="price-excluding-tax" data-label="<?= $escaper->escapeHtmlAttr(__('Excl. Tax')) ?>">
                                                <?= /* @noEscape */ $formatterViewModel->currency($item['row_total']) ?>
                                            </span>
                                        <?php endif ?>
                                    </div>
                                </div>

                                <?php $optionsRenderer = $cartItemsViewModel->getProductOptionsRenderer($block, $item['product_type']) ?>

                                <?php if ($optionsRenderer): ?>
                                    <?= /* @noEscape */ $optionsRenderer->setData('quote_item', $item)->toHtml() ?>
                                <?php endif ?>
                            </div>
                        </div>
                    <?php endforeach ?>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>
<script>
    <?php /** Generated with hyva-csp-helper.php */ ?>

    function TechticHyvaChildHyvaCheckoutPriceSummaryCartItems() {
        return Object.assign({
            expand: this.$wire.expand
        }, {
            ['TechticHyvaChildHyvaCheckoutPriceSummaryCartItemsClass232']() {
                return {
                    'rotate-180': this.expand
                }
            },
            ['TechticHyvaChildHyvaCheckoutPriceSummaryCartItemsClick231'](event) {
                return this.expand = !this.expand
            },
        })
    }
    window.addEventListener('alpine:init', () => Alpine.data('TechticHyvaChildHyvaCheckoutPriceSummaryCartItems', TechticHyvaChildHyvaCheckoutPriceSummaryCartItems), {
        once: true
    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>