<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<div class="flex flex-col md:gap-x-6 lg:flex-row gap-y-6 ">
    <div class="column column-main w-full lg:w-1/3 space-y-5 h-full">
        <?= $block->getChildHtml('column.main') ?>
    </div>

    <div class="column column-center w-full lg:w-1/3 space-y-5 h-full">
        <?= $block->getChildHtml('column.center') ?>
    </div>

    <div class="column column-right w-full lg:w-1/3 space-y-5 h-full">
        <?= $block->getChildHtml('column.right') ?>
        <?= $block->getChildHtml('hyva.checkout.navigation') ?>
    </div>
</div>
