<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Request a Quote Hyva Compatibility
 */

use Magento\Framework\Escaper;

/** @var Escaper $escaper */
?>
<div x-data="initGrandTotalSegment">
    <template x-if="isGrandTotal">
        <div class="flex pt-4 md:grid md:grid-cols-2 md:w-full text-lg text-teak-ink leading-none font-garamond capitalize">
            <h3 class="w-7/12 text-left md:w-auto">
                <?= $escaper->escapeHtml(__('Quote Total')) ?>
            </h3>
            <div class="w-5/12 text-right md:w-auto text-xl"
                x-text="formatGrandTotal"></div>
        </div>
    </template>
</div>

<script>
    if (typeof initGrandTotalSegment !== "function") {
        function initGrandTotalSegment() {
            return {
                isGrandTotal() {
                    return this.segment.code === 'grand_total';
                },

                formatGrandTotal() {
                    return hyva.formatPrice(this.segment.value);
                }
            };
        }
        window.addEventListener('alpine:init', () => Alpine.data('initGrandTotalSegment', initGrandTotalSegment), {
            once: true
        })
    }
</script>
<?php $hyvaCsp->registerInlineScript() ?>