<div x-data="initSubtotalSegment">
    <template x-if="isSubtotal">
        <div class="flex py-2.5 text-sm font-normal md:grid md:grid-cols-2 md:w-full text-teak-muted">
            <div class="w-7/12 text-left md:w-auto"
                x-html="segment.title"></div>
            <div class="w-5/12 text-right md:w-auto font-mono text-teak-ink"
                x-text="formatSubtotal"></div>
        </div>
    </template>
</div>

<script>
    if (typeof initSubtotalSegment !== "function") {
        function initSubtotalSegment() {
            return {
                isSubtotal() {
                    return this.segment.code === 'subtotal';
                },
                formatSubtotal() {
                    return hyva.formatPrice(this.segment.value);
                }
            };
        }

        window.addEventListener('alpine:init', () => Alpine.data('initSubtotalSegment', initSubtotalSegment), {
            once: true
        })
    }
</script>
<?php $hyvaCsp->registerInlineScript() ?>