<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Most Viewed or Automatic Related Products Hyva Compatibility by Amasty
 */
?>
<?php
use Amasty\Mostviewed\Block\Widget\Related;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\Wishlist;
use Hyva\Theme\ViewModel\ProductPage;
use Amasty\Mostviewed\Model\OptionSource\BlockPosition;
use Amasty\Mostviewed\Model\ResourceModel\RuleIndex;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Related $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
// phpcs:disable Generic.Files.LineLength.TooLong
?>

<?php if ($block->getProductCollection() && $block->getProductCollection()->getSize()): ?>
    <?php
    $image = 'related_products_content';
    $items = $block->getProductCollection()->getItems();
    $itemsCount = count($items);
    $isSlider = $block->getBlockLayout();
    $showWishlist = $block->getDisplayButtonWishlist();
    $showCompare = $block->getDisplayButtonCompare();
    $showCart = $block->getAddToCart();
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $pageLayout = $block->getLayout()->getUpdate()->getPageLayout();
    $isTwoColumnsLayout = str_contains($pageLayout, "2columns");
    $productItemClasses = $isTwoColumnsLayout ? "sm:w-1/2 xl:w-1/3" : "md:w-1/2 lg:w-1/3 xl:w-1/4";
    ?>

    <?php if ($isSlider): ?>
        <script>
            'use strict';

            function initAmRelatedProductsSliderComponent<?= (int)$block->getGroupId();?>() {
                return {
                    active: 0,
                    itemCount: 0,
                    getSlider() {
                        return (this.$root) ? this.$root.querySelector('.js_slides') : this.$el.querySelector('.js_slides')
                    },
                    pageSize: 4,
                    pageFillers: 0,
                    calcPageSize() {
                        const slider = this.getSlider();
                        if (slider) {
                            this.itemCount = slider.querySelectorAll('.js_slide').length;
                            this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                            this.pageFillers = (
                                this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                            ) - this.itemCount;
                        }
                    },
                    calcActive() {
                        const slider = this.getSlider();
                        if (slider) {
                            const sliderItems = this.itemCount + this.pageFillers;
                            const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
                            this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                        }
                    },
                    scrollPrevious() {
                        this.scrollTo(this.active - this.pageSize);
                    },
                    scrollNext() {
                        this.scrollTo(this.active + this.pageSize);
                    },
                    scrollTo(idx) {
                        const slider = this.getSlider();
                        if (slider) {
                            const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                            slider.scrollLeft = Math.floor(slideWidth) * idx;
                            this.active = idx;
                        }
                    }
                }
            }
        </script>
    <?php endif; ?>

    <?php if ($showWishlist): ?>
        <script>
            function initAmWishlist() {
                return {
                    addToWishlist(productId) {
                        const formKey = hyva.getFormKey();
                        const postUrl = BASE_URL + 'wishlist/index/add/';

                        fetch(postUrl, {
                            "headers": {
                                "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                            },
                            "body": "form_key=" + formKey + "&product=" + productId + "&uenc=" + hyva.getUenc(),
                            "method": "POST",
                            "mode": "cors",
                            "credentials": "include"
                        }).then(function (response) {
                            if (response.redirected) {
                                window.location.href = response.url;
                            } else if (response.ok) {
                                return response.json();
                            } else {
                                typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                    [{
                                        type: "warning",
                                        text: "<?= $escaper->escapeHtml(__('Could not add item to wishlist.')) ?>"
                                    }], 5000
                                );
                            }
                        }).then(function (response) {
                            if (!response) { return }
                            typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                [{
                                    type: (response.success) ? "success" : "error",
                                    text: (response.success)
                                        ? "<?= $escaper->escapeHtml(__("%1 has been added to your Wish List.", __("Product"))) ?>"
                                        : response.error_message
                                }], 5000
                            );
                            const reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                            window.dispatchEvent(reloadCustomerDataEvent);
                        }).catch(function (error) {
                            typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                [{
                                    type: "error",
                                    text: error
                                }], 5000
                            );
                        });
                    }
                }
            }
        </script>
    <?php endif; ?>

    <?php if ($showCompare): ?>
        <script>
            function initAmCompareOnProductList() {
                return {
                    addToCompare(productId) {
                        const formKey = hyva.getFormKey();
                        const postUrl = BASE_URL + 'catalog/product_compare/add/';

                        fetch(postUrl, {
                            "headers": {
                                "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                            },
                            "body": "form_key=" + formKey + "&product=" + productId + "&uenc=" + hyva.getUenc(),
                            "method": "POST",
                            "mode": "cors",
                            "credentials": "include"
                        }).then(function (response) {
                            if (response.redirected) {
                                window.location.href = response.url;
                            }
                        }).catch(function (error) {
                            typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                [{
                                    type: "error",
                                    text: error
                                }], 5000
                            );
                        });
                    }
                };
            }
        </script>
    <?php endif; ?>

    <div class="widget my-6 text-gray-700 body-font md:my-8 xl:my-12 <?= /* @noEscape */ $block->getCssClass() ?>"
         id="amrelated-block-<?= (int)$block->getGroupId();?>"
        <?php if ($isSlider): ?>
            x-data="initAmRelatedProductsSliderComponent<?= (int)$block->getGroupId();?>()"
            x-init="calcPageSize();"
            @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })"
        <?php endif; ?>
    >
        <?php if ($block->getTitle()
            && $block->getData(RuleIndex::POSITION) !== BlockPosition::PRODUCT_CONTENT_TAB): ?>
            <div class="flex flex-col items-center pt-6 pb-3 mx-auto mb-6 md:flex-row">
                <h4 class="text-center text-2xl font-medium text-gray-900 title-font">
                    <?= $escaper->escapeHtml(__($block->getTitle())) ?>
                </h4>
            </div>
        <?php endif; ?>

        <div class="w-full relative <?= $isSlider ? 'overflow-x-hidden' : '' ?>">
            <div class="flex w-full <?= $isSlider ? 'js_slides snap overflow-auto' : 'flex-wrap' ?>"
                <?= $isSlider ? '@scroll.debounce="calcActive"' : '' ?>
            >
                <?php foreach ($items as $item): ?>
                    <div class="flex flex-shrink-0 w-full p-2 <?= /* @noEscape */ $productItemClasses ?> <?= $isSlider ? 'js_slide' : '' ?>">
                        <div class="item product product-item card card-interactive flex flex-col w-full">
                            <a href="<?= $escaper->escapeUrl($block->getProductUrl($item)) ?>"
                               class="product photo product-item-photo block mx-auto mb-3">
                                <img src="<?= $escaper->escapeHtmlAttr($block->getImage($item, $image)->getImageUrl()) ?>"
                                     class="hover:shadow-sm object-contain product-image-photo"
                                     alt="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"/>
                            </a>

                            <div class="product-info flex flex-col flex-grow">
                                <div class="mt-2 mb-1 text-primary font-semibold text-lg text-center h-14">
                                    <a title="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                       href="<?= $escaper->escapeUrl($block->getProductUrl($item)) ?>"
                                       class="product-item-link">
                                        <?= $escaper->escapeHtml($item->getName()) ?>
                                    </a>
                                </div>

                                <?php if ($templateType && $reviewsSummary = $block->getReviewsSummaryHtml($item, $templateType)): ?>
                                    <div class="py-1 mx-auto">
                                        <?= /* @noEscape */ $reviewsSummary ?>
                                    </div>
                                <?php endif; ?>

                                <?php if ($productPrice = $block->getProductPriceHtml($item, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE)): ?>
                                    <div class="pt-1 text-gray-900 mt-auto">
                                        <?= /* @noEscape */ $productPrice ?>
                                    </div>
                                <?php endif; ?>

                                <?php if ($brandLogo = $block->getBrandLogoHtml($item)): ?>
                                    <div class="py-1 mx-auto">
                                        <?= /* @noEscape */ $brandLogo ?>
                                    </div>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="mt-auto pt-3 flex flex-wrap justify-center items-center">
                                        <?php if ($showCart): ?>
                                            <?php if ($item->isSaleable()): ?>
                                                <form method="post"
                                                      action="<?= $escaper->escapeUrl($productViewModel->getAddToCartUrl($item, ['useUencPlaceholder' => true])) ?>"
                                                      class="mr-auto product_addtocart_form"
                                                    <?php if ($item->getOptions()): ?>
                                                        enctype="multipart/form-data"
                                                    <?php endif; ?>
                                                >
                                                    <?= /** @noEscape */ $block->getBlockHtml('formkey') ?>
                                                    <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr((int)$item->getId())?>"/>
                                                    <button class="btn btn-primary w-auto justify-center text-sm mr-auto mb-2"
                                                            type="submit"
                                                            data-amrelated-button="tocart"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                        <?= $heroicons->shoppingCartHtml("h-6 w-6 border-current inline", 25, 25) ?>
                                                        <span class="hidden ml-2 md:ml-0 md:inline lg:ml-2">
                                                        <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                    </span>
                                                    </button>
                                                </form>

                                            <?php else: ?>
                                                <div class="w-auto justify-center mr-auto">
                                                    <div class="text-right">
                                                        <?php if ($item->getIsSalable()): ?>
                                                            <p class="stock available flex items-center justify-end align-middle gap-x-2"
                                                               title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
                                                                <span class="w-3 h-3 bg-green-500 rounded-full flex-shrink-0"></span>
                                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                                            </p>
                                                        <?php else: ?>
                                                            <p class="stock unavailable flex items-center justify-end align-middle gap-x-2"
                                                               title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
                                                                <span class="w-3 h-3 bg-red-500 rounded-full flex-shrink-0"></span>
                                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                                            </p>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                        <?php if ($showWishlist || $showCompare): ?>
                                            <?php if ($wishlistViewModel->isEnabled() && $showWishlist): ?>
                                                <button x-data="initAmWishlist()"
                                                        @click.prevent="addToWishlist(<?= (int)$item->getId() ?>)"
                                                        aria-label="<?= $escaper->escapeHtmlAttr(__('Am Add to Wish List')) ?>"
                                                        type="button"
                                                        class="rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex
                                                         flex-shrink-0 items-center justify-center text-gray-500
                                                         hover:text-red-600 ml-2">
                                                    <?= $heroiconsSolid->heartHtml("w-5 h-5", 25, 25) ?>
                                                </button>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <button x-data="initAmCompareOnProductList()"
                                                        @click.prevent="addToCompare(<?= (int)$item->getId() ?>)"
                                                        aria-label="<?= $escaper->escapeHtmlAttr(__('Am Add to Compare')) ?>"
                                                        type="button"
                                                        class="rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex
                                                        flex-shrink-0 items-center justify-center text-gray-500
                                                        hover:text-yellow-500 ml-2">
                                                    <?= $heroicons->scaleHtml("w-5 h-5", 25, 25) ?>
                                                </button>
                                            <?php endif; ?>
                                            <?php // phpcs:enable ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>

                <?php if ($isSlider): ?>
                    <div :class="{
                        'js_dummy_slide w-full flex flex-shrink-0 py-1 <?= /* @noEscape */ $productItemClasses ?>'
                        : pageFillers > 0
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full flex flex-shrink-0 py-1 <?= /* @noEscape */ $productItemClasses ?>'
                        : pageFillers > 1
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full flex flex-shrink-0 py-1 <?= /* @noEscape */ $productItemClasses ?>'
                        : pageFillers > 2
                        }"></div>
                <?php endif; ?>
            </div>
        </div>

        <?php if ($isSlider): ?>
            <div style="min-height: 65px">
                <template x-if="itemCount > pageSize">
                    <div class="flex items-center justify-center py-4">
                        <button
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Previous')) ?>"
                            tabindex="-1"
                            class="mr-4 text-black rounded-full outline-none focus:outline-none flex-none"
                            :class="{ 'opacity-25 pointer-events-none' : active === 0 }"
                            @click="scrollPrevious">
                            <?= $heroicons->chevronLeftHtml("w-5 h-5", 25, 25) ?>
                        </button>
                        <div class="flex flex-wrap w-full md:w-auto justify-center">
                            <?php for ($i = 0; $i < $itemsCount; $i++): ?>
                                <span class="flex-shrink-0 block w-3 h-3 m-1 bg-black bg-opacity-25 rounded-full shadow
                                        cursor-pointer"
                                      :class="{
                                            'bg-opacity-100': active === <?= (int) $i ?>,
                                            'hidden': (pageSize !== 1 && !!(<?= (int) $i ?> % pageSize))
                                          }"
                                      @click="scrollTo(<?= (int) $i ?>)">
                            </span>
                            <?php endfor; ?>
                        </div>
                        <button
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Next')) ?>"
                            tabindex="-1"
                            class="ml-4 text-black rounded-full outline-none focus:outline-none flex-none"
                            :class="{ 'opacity-25 pointer-events-none' : active >= itemCount-pageSize }"
                            @click="scrollNext">
                            <?= $heroicons->chevronRightHtml("w-5 h-5", 25, 25) ?>
                        </button>
                    </div>
                </template>
            </div>
        <?php endif; ?>
    </div>
<?php endif;?>
