<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductCompare;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);

/** @var Product $product */
$product = $currentProduct->get();

if (!$product->getId() || !$compareViewModel->showOnProductPage()) {
    return;
}
?>
<script>
    function initCompareOnProductView() {
        return {
            addToCompare: function(productId) {
                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'catalog/product_compare/add/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&product=" + productId + "&uenc=" + hyva.getUenc(),
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(function(response) {
                    if (response.redirected) {
                        window.location.href = response.url;
                    }
                }).catch(function(error) {
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: error
                        }], 5000
                    );
                });
            }
        };
    }
</script>

<button x-data="initCompareOnProductView()"
    @click.prevent="addToCompare(<?= (int)$product->getId() ?>)"
    title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
    id="add-to-compare"
    class="rounded-full w-10 md:w-12 h-10 md:h-12 p-0 inline-flex items-center justify-center border-2 border-[#d4b27080]"
    data-addto="compare">
    <svg class="w-6 h-6" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M3 6.5L6 7.5M6 7.5L3 16.5C4.77253 17.8334 7.22866 17.8334 9.00119 16.5M6 7.5L9.00006 16.5M6 7.5L12 5.5M18 7.5L21 6.5M18 7.5L15 16.5C16.7725 17.8334 19.2287 17.8334 21.0012 16.5M18 7.5L21.0001 16.5M18 7.5L12 5.5M12 3.5V5.5M12 21.5V5.5M12 21.5H9M12 21.5H15" stroke="#D1AD66" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
</button>