<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Catalog\Block\Product\View\Attributes;
use Magento\Catalog\Model\Product;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var CatalogOutputHelper $output */
/** @var Attributes $block */

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);

/** @var Product $product */
$product = $block->getProduct();

$getLayoutStyle = (string) $block->getLayoutStyle() ?: "";

$layoutStyleTableRow = $getLayoutStyle === "" ? "table-row" : ($getLayoutStyle === "list" ? "block" : "");
$layoutStyleTableCellHeading = $getLayoutStyle === ""
    ? "py-3"
    : ($getLayoutStyle === "list" ? "block pt-3 px-3" : "py-2 px-3");
$layoutStyleTableCellItem = $getLayoutStyle === ""
    ? "py-3"
    : ($getLayoutStyle === "list" ? "block pb-3 px-3" : "py-2 px-3");
?>

<?php if ($attributes = $block->getAdditionalData()): ?>
    <div class="table-wrapper overflow-x-auto" id="product-attributes">
        <table class="additional-attributes table-fixed w-full">
            <?php foreach ($attributes as $attribute): ?>
                <tr class="bg-transparent border-b first:border-t border-x border-[#0000004D]  <?= $layoutStyleTableRow ?>">
                    <th
                        class="col label px-2 product-attribute-label text-start text-[#666666] text-base break-words hyphens-auto <?= $layoutStyleTableCellHeading ?>"
                        scope="row"
                    ><?= $escaper->escapeHtml($attribute['label']) ?></th>
                    <td
                        class="col data product-attribute-value text-start text-[#666666] text-base break-words hyphens-auto <?= $layoutStyleTableCellItem ?>"
                        data-th="<?= $escaper->escapeHtmlAttr($attribute['label']) ?>"
                    ><?= /* @noEscape */ $catalogOutputHelper->productAttribute($product, $attribute['value'], $attribute['code']) ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
<?php endif;?>
