<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;

/** @var \Magento\Framework\View\Element\Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var CurrentProduct $currentProduct */

$currentProduct = $viewModels->require(CurrentProduct::class);
/** @var Product $product */
$product = $block->getData('product') ?: $currentProduct->get();

if (!$product || !$product->getId()) {
    return;
}

$baseUrl = $block->getBaseUrl(); // Gets base site URL
$manufacturerOptionId = $product->getData('manufacturer'); // Get selected option ID
if ($product) {
    $manufacturer = $product->getAttributeText('manufacturer');
    if (!empty($manufacturer) && strtolower(trim($manufacturer)) === 'tower living'): ?>
        <a href="<?= $baseUrl . 'wonen?manufacturer=' . $manufacturerOptionId; ?>"
            class="flex items-center justify-center w-full bg-techtic-terracotta rounded-lg py-3.5 px-7 my-5">
            <span class="text-white text-sm leading-5 px-4 uppercase font-semibold">
                <?= $block->escapeHtml(__('Prefer to see it first? Visit our showroom and explore the Tower Living collection')) ?>
            </span>
        </a>
<?php endif;
}
?>