<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Request a Quote Hyva Compatibility
 */

use Amasty\RequestQuote\Block\Account\Quote\History;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;

/** @var History $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$quotes = $block->getQuotes();
$heroIcons = $viewModels->require(HeroiconsSolid::class);
?>

<h2 class="text-2xl mb-6"><?= $escaper->escapeHtml(__('My Quotes')) ?></h2>

<?php if ($quotes && $quotes->getSize()): ?>
    <div class="card grid <?= $block->isExpiryColumnShow() ? 'grid-cols-4 lg:grid-cols-6' : 'grid-cols-3 lg:grid-cols-5 ' ?> mb-4 flex">
        <div class="text-sm text-secondary p-2"><?= $escaper->escapeHtml(__('Quote #')) ?></div>
        <div class="text-sm hidden lg:block text-secondary p-2"><?= $escaper->escapeHtml(__('Date')) ?></div>
        <div class="text-sm hidden lg:block text-secondary p-2"><?= $escaper->escapeHtml(__('Quote Total')) ?></div>
        <div class="text-sm lg:block text-secondary p-2"><?= $escaper->escapeHtml(__('Status')) ?></div>
        <?php if ($block->isExpiryColumnShow()): ?>
            <div class="text-sm lg:block text-secondary p-2"><?= $escaper->escapeHtml(__('Expiry Date')) ?></div>
        <?php endif; ?>
        <div class="text-sm lg:block text-secondary p-2">
            <?= $escaper->escapeHtml(__('View')) ?> / <?= $escaper->escapeHtml(__('Move to Cart')) ?>
        </div>
        <?php $i = 0; ?>
        <?php foreach ($quotes as $quote): ?>
            <?php $i++; ?>
            <div class="p-2 flex items-center">
                <?= $escaper->escapeHtml($quote->getIncrementId()) ?>
            </div>
            <div class="p-2 hidden lg:flex items-center">
                <?= $escaper->escapeHtml($block->formatDate($quote->getCreatedAt())) ?>
            </div>
            <div class="p-2 hidden lg:flex items-center">
                <?= /* @noEscape */ $quote->formatPrice($quote->getGrandTotal()) ?>
            </div>
            <div class="p-2 flex items-center">
                <?= $escaper->escapeHtml($quote->getStatusLabel()) ?>
            </div>
            <?php if ($block->isExpiryColumnShow()): ?>
                <div class="p-2 flex items-center text-center">
                    <?= $escaper->escapeHtml($block->getExpiredDate($quote)) ?>
                </div>
            <?php endif; ?>
            <div class="p-2 flex items-center gap-5">
                <a href="<?= $escaper->escapeUrl($block->getViewUrl($quote)) ?>"
                    class="inline-block text-sm underline text-secondary-darker"
                    title="<?= $escaper->escapeHtmlAttr(__('View Quote')) ?>">
                    <?= $heroIcons->eyeHtml() ?>
                    <span class="sr-only"><?= $escaper->escapeHtml(__('View Quote')) ?></span>
                </a>
                <?php if ($block->isMoveShowed($quote)): ?>
                    <?php $formData = json_decode($block->getPostData($block->getMoveUrl($quote)), true); ?>
                    <form action="<?= $escaper->escapeUrl($formData['action']) ?>" method="post" class="flex">
                        <?= $block->getBlockHtml('formkey'); ?>
                        <input type="hidden" name="data"
                            value="<?= $escaper->escapeHtmlAttr(json_encode($formData['data'])) ?>" />
                        <button title="<?= $escaper->escapeHtmlAttr(__('Move to Cart')) ?>"
                            type="submit"
                            class="inline-block text-sm underline text-secondary-darker">
                            <?= $heroIcons->shoppingCartHtml() ?>
                            <span class="sr-only"><?= $escaper->escapeHtml(__('Move to Cart')) ?></span>
                        </button>
                    </form>
                <?php endif; ?>
                <?= /* @noEscape */ $block->getAdditionalActions($quote) ?>
            </div>
        <?php endforeach; ?>
    </div>

    <?php if ($block->getPagerHtml()): ?>
        <div class="quote-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml(__('You have placed no quotes.')) ?></span></div>
<?php endif ?>