const {
    spacing
} = require('tailwindcss/defaultTheme');

const colors = require('tailwindcss/colors');

const hyvaModules = require('@hyva-themes/hyva-modules');

module.exports = hyvaModules.mergeTailwindConfig({
    theme: {
        container: {
            center: true,
            screens: {
                sm: '576px',
                smd: '640px',
                md: '768px',
                ml: '991px',
                lg: '1024px',
                xl: '1280px',
                '2xl': '1320px' // force 2xl to stay at 1320px
            }
        },
        extend: {
            screens: {
                'sm': '576px',
                // => @media (min-width: 576px) { ... }
                'smd': '640px',
                // => @media (min-width: 640px) { ... }
                'md': '768px',
                // => @media (min-width: 768px) { ... }
                'ml': '991px',
                // => @media (min-width: 991px) { ... }
                'lg': '1024px',
                // => @media (min-width: 1024px) { ... }
                'xl': '1280px',
                // => @media (min-width: 1280px) { ... }
                '2xl': '1320px' // => @media (min-width: 1320px) { ... }

            },
            fontFamily: {
                sans: ['Mulish', 'sans-serif'],
                garamond: ['Garamond'],

            },
            colors: {
                primary: {
                    lighter: colors.blue['300'],
                    "DEFAULT": '#D1AD65',
                    darker: colors.blue['900']
                },
                secondary: {
                    lighter: colors.blue['100'],
                    "DEFAULT": colors.blue['200'],
                    darker: colors.blue['300']
                },
                'techtic-brown': '#D1AD65',
                'techtic-black': '#1E1E1E',
                background: {
                    lighter: colors.blue['100'],
                    "DEFAULT": colors.blue['200'],
                    darker: colors.blue['300'],
                    'techtic': '#FAF7F0',
                    'techtic-red': '#A01937'
                },
                green: colors.emerald,
                yellow: colors.amber,
                purple: colors.violet,
                'techtic-red': '#A01937',
                'techtic-dark-brown': '#614214',
                'techtic-yellow': '#D1AD65',
                'techtic-white': '#E7E7E7',
                'techtic-warm-white': '#F9F6F1',
                'techtic-white-beige': '#F1ECE1',
                'techtic-gold': '#F5A623',
                'techtic-lighter-yellow': '#FFF3DA',
                'techtic-gray': '#646464',
                'techtic-dark-gray': '#393939',
                'techtic-neutral': '#0A0A0A',
                'techtic-neutral-dark': '#333333',
                'techtic-light-gray': '#D8D8D8',
                'techtic-green': '#47BF0F',
                'techtic-light-green': '#43A047',
                'techtic-deep-green': '#1C3B2F',
                'techtic-terracotta': '#D35400',
                'techtic-lime-green': '#009844',
                'techtic-checkout-light-green': '#14ac00',
                'techtic-lighter-gray': "#F5F5F5",
                'teak-ink': "#1A1A1A",
                'teak-green': "#1E4D2B",
                'teak-light-green': "#1E4D2B0F",
                'teak-gold': "#C49A28",
                'teak-muted': "#6b6b6b",
                'techtic-highlight-red': '#FF0000',
            },
            textColor: {
                orange: colors.orange,
                primary: {
                    lighter: colors.gray['700'],
                    "DEFAULT": '#1f2937',
                    darker: colors.gray['900']
                },
                secondary: {
                    lighter: colors.gray['400'],
                    "DEFAULT": colors.gray['600'],
                    darker: colors.gray['800']
                },
                tertiary: {
                    "DEFAULT": '#D1AD65'
                },
                'techtic-tomato-red': '#D0021B',
                'techtic-traffic-green': '#00A000',
                'techtic-checkout-green': '#15b500',
                'techtic-brown': '#8B4513'

            },
            backgroundColor: {
                primary: {
                    "DEFAULT": '#D35400'
                },
                secondary: {
                    lighter: '#FAF7F0',
                    "DEFAULT": '#FAF7F0',
                    darker: '#FAF7F0'
                },
                tertiary: {
                    "DEFAULT": '#2F2F2F'
                },
                container: {
                    lighter: '#ffffff',
                    "DEFAULT": '#ffffff',
                    darker: '#2F2F2F'
                },
                'techtic': '#FAF7F0',
                'techtic-gold': '#F5A623',
                'techtic-cream': '#FFFAEF',
                'techtic-terracotta': '#D35400',
                'techtic-lime-green': '#009844',
                'techtic-checkout-green': '#15b500',
                'teak-stone-light': '#FAFAF7'
            },
            borderColor: {
                primary: {
                    "DEFAULT": '#D1AD66'
                },
                secondary: {
                    "DEFAULT": "#4F4F4F"
                },
                container: {
                    lighter: '#f5f5f5',
                    "DEFAULT": '#e7e7e7',
                    darker: '#b6b6b6'
                },
                'techtic-tomato-red': '#D0021B',
            },
            minWidth: {
                8: spacing["8"],
                20: spacing["20"],
                40: spacing["40"],
                48: spacing["48"]
            },
            minHeight: {
                14: spacing["14"],
                a11y: '44px',
                'screen-25': '25vh',
                'screen-50': '50vh',
                'screen-75': '75vh'
            },
            maxHeight: {
                '0': '0',
                'screen-25': '25vh',
                'screen-50': '50vh',
                'screen-75': '75vh'
            },
            container: {
                center: true,
                padding: '1.5rem'
            }
        }
    },
    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography'), require('@tailwindcss/line-clamp')],
    // Examples for excluding patterns from purge
    content: [
        // this theme's phtml and layout XML files
        '../../**/*.phtml',
        '../../*/layout/*.xml',
        '../../*/page_layout/override/base/*.xml',
        // parent theme in Vendor (if this is a child-theme)
        '../../../../../../../vendor/hyva-themes/magento2-default-theme/**/*.phtml',
        '../../../../../../../vendor/hyva-themes/magento2-default-theme/*/layout/*.xml',
        '../../../../../../../vendor/hyva-themes/magento2-default-theme/*/page_layout/override/base/*.xml',
        // app/code phtml files (if need tailwind classes from app/code modules)
        //'../../../../../../../app/code/**/*.phtml',
    ],
    safelist: [
        'ml:flex-row',
        'text-neutral-950',
        'text-techtic-red',
        'text-[#13895C]',
        'text-[#A5813B]',
        'bg-techtic-lighter-yellow',
        '!lg:border-r-0',
        'lg:w-[260px]',
        '!lg:w-[470px]',
        'max-w-36',
        'max-h-36',
        'max-w-[430px]',
        '-bottom-14',
        'md:-right-14',
        'xl:-bottom-5',
        'xl:-left-12',
        'bottom-10',
        'font-light',
        'text-techtic-green',
        'bg-techtic-light-green',
        'after:bg-primary',
        'bg-techtic-terracotta',
        'bg-techtic-gray',
        'bg-[#A9E5A1]',
        'bg-[#FFE9A1]',
        'bg-[#CDE3FF]',
        'bg-[#FFD8A8]',
        'bg-[#FFC4B3]',
        'bg-[#DAD0FF]',
        'bg-[#ffe3d0]',
        'bg-[#FFFFFFB2]',
        'bg-[#282828]',
        'font-garamond',
        'bg-techtic-neutral',
        'min-h-[500px]',
        'lg:min-h-[600px]',
        'text-[32px]',
        'lg:text-[68px]',
        'lg:mb-[22px]',
        'w-[94px]',
        'h-[34px]',
        'grid-cols-[146px_1fr]',
        'lg:grid-cols-[345px_1fr]',
        'lg:gap-14',
        'lg:px-4',
        'my-auto',
        'lg:my-0',
        'my-[10px]',
        'lg:my-4',
        'w-[18px]',
        'lg:w-8',
        'h-[18px]',
        'text-[#A01937]',
        '!mb-0',
        'lg:w-[33%]',
        'group-hover:scale-110',
        'lg:p-6',
        'bg-[#0000004D]',
        'lg:text-[50px]',
        'lg:leading-none',
        'lg:font-bold',
        'lg:my-5',
        'bg-[#A01937]',
        'hover:pr-4',
        'hover:bg-white',
        'hover:text-[#A01937]',
        'sm:opacity-0',
        'group-hover:opacity-100',
        'group-hover:translate-x-0',
        'group-hover:w-5',
        'group-hover/btn:w-5',
        'sm:gap-6',
        'sm:gap-14',
        'sm:w-[45%]',
        'lg:w-[40%]',
        'xl:w-[30%]',
        'lg:w-[67%]',
        'content-end',
        'lg:text-[40px]',
        'mb-[revert]',
        'group',
        'group-hover:scale-110',
        'from-black/80',
        'to-transparent',
        'lg:[34px]',
        'max-w-full',
        'lg:max-w-sm',
        'group/btn',
        'lg:mt-16',
        '!mb-0',
        'from-30%',
        'via-black/60',
        'to-black/10',
        'from-black',
        'lg:bg-gradient-to-l',
        'lg:from-40%',
        'lg:via-black/80',
        'lg:to-black/40',
        'items-end',
        'justify-left',
        'lg:px-6',
        'text-[10px]',
        'max-w-[400px]',
        'lg:pr-6',
        'border-r',
        'h-4',
        'lg:h-6',
        'lg:h-8',
        'lg:py-[8px]',
        'lg:top-10',
        'lg:text-[30px]',
        'lg:my-6',
        'lg:py-3',
        'lg:py-15',
        'mt-14',
        'xl:w-32',
        'xl:h-[340px]',
        'w-56',
        'xl:w-[265px]',
        'min-h-[700px]',
        'sm:min-h-[570px]',
        'l:min-h-[600px]',
        'max-w-[855px]',
        'xl:text-[54px]',
        'xl:text-lg',
        'hover:border-[#A01937]',
        'lg:py-10',
        'lg:gap-6',
        'text-[22px]',
        'lg:text-[26px]',
        'text-[#A0A0A2]',
        'm-2.5',
        'lg:m-14',
        'lg:w-[558px]',
        'lg:h-[610px]',
        'xl:h-[575px]',
        'xl:px-10',
        'ml:sticky',
        'md:gap-x-10',
        'lg:gap-x-2.5',
        'lg:my-10',
        'md:px-10',
        'h-40',
        'xl:w-48',
        'xl:h-48',
        'xl:max-w-48',
        'xl:max-h-48',
        'md:mb-0',
        'lg:mt-8',
        'lg:w-[650px]',
        'xl:h-[535px]',
        'h-[500px]',
        'ml:mt-0',
        'divide-y',
        'divide-gray-200',
        'group-open:rotate-45',
        'lg:w-[76px]',
        'lg:w-[124px]',
        'lg:py-6',
        'w-[108px]',
        'lg:w-32',
        'lg:min-h-[545px]',
        'lg:gap-24',
        'text-[#2F3A2E]',
        'border-[#C7B79C]',
        'text-[#6B5E3B]',
        'bg-[#6B5E3B]',
        'hover:bg-[#5A4F32]',
        'bg-black/35',
        'group-hover:bg-black/45',
        'bottom-6',
        'left-6',
        'h-[271px]',
        'left-5',
        'lg:left-14',
        'bottom-14',
        'lg:mb-0',
        'rounded-t-[20px]',
        'lg:rounded-tl-[40px]',
        'rounded-b-[20px]',
        'lg:rounded-tr-[40px]',
        'lg:rounded-bl-[40px]',
        'lg:rounded-br-[40px]',
        'lg:rounded-tr-none',
        'lg:rounded-br-none',
        'lg:rounded-b-none',
        'lg:rounded-t-none',
        'lg:h-[400px]',
        'lg:w-[458px]',
        'py-12',
        'bg-green-50',
        'border-green-200',
        'text-green-800',
        'border-techtic-deep-green',
        'text-techtic-deep-green',
        'text-techtic-warm-white',
        'bg-techtic-warm-white',
        'bg-techtic-dark-brown',
        'ring-techtic-dark-brown',
        'hover:bg-techtic-deep-green',
        'from-[#1e4d2beb]',
        'to-[#0F5B2F]',
        'font-serif',
        'text-[#D5A623]',
        'from-[#3A5A40]',
        'to-[#1E4D2B]',
        'bg-[#D5A623]',
        'from-[#5C6B73]',
        'to-[#253237]',
        'from-[#5A7642]',
        'sm:border-r',
        'sm:sticky',
        'sm:top-6',
        'sm:h-screen'
    ]
});
