<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Navigation\Checkout;
use Hyva\Checkout\ViewModel\Navigation;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Checkout $checkout */

/** @var Navigation $navigation */
$navigation = $viewModels->require(Navigation::class);

$navigator = $navigation->getNavigator();
$checkout  = $navigator->getActiveCheckout();
?>

<?php if ($checkout->hasSteps() && $checkout->isMultiStepper()): ?>
    <?php $previous = $checkout->getStepBefore($navigator->getActiveStep()) ?>
    <?php $next = $checkout->getStepAfter($navigator->getActiveStep()) ?>

    <?php if ($navigation->getSystemConfig()->showNavigationBackButton()): ?>
        <?php if ($previous): ?>
            <button
                type="button"
                rel="prev"
                class="relative group flex items-center justify-center 
                        disabled:opacity-10 disabled:cursor-not-allowed 
                        text-sm text-teak-muted hover:text-teak-green 
                        underline-offset-4 hover:underline btn-previous"
                data-route="<?= $escaper->escapeHtmlAttr($previous->getRoute()) ?>"
                x-bind="buttonPrevious">
                <span class="group-disabled:invisible">
                    <?= $escaper->escapeHtml(__('Back to %1', __($previous->getLabel('previous step')))) ?>
                </span>

                <span class="hidden group-disabled:flex absolute inset-0 justify-center items-center p-2">
                    <?= $block->getChildHtml('loader') ?>
                </span>
            </button>
        <?php elseif ($navigation->getSystemConfig()->showNavigationBackToCartButton()): ?>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>"
                class="btn btn-secondary"><?= $escaper->escapeHtml(__('Back to Cart')) ?></a>
        <?php endif ?>
    <?php endif ?>

    <?php if ($next): ?>
        <div class="fixed bottom-0 left-0 right-0 z-40 bg-white p-1.5 w-full
                sm:static sm:z-auto sm:bg-transparent sm:p-0 sm:m-0
                shadow-[0px_-6px_13px_0px_rgba(0,0,0,0.10)] sm:shadow-none">
        <button
            type="button"
            rel="next"
            class="group flex items-center gap-x-1 w-full justify-center py-2.5 px-6 
            rounded-lg uppercase disabled:opacity-10 disabled:cursor-not-allowed 
            bg-teakea-red text-white font-normal text-base"

            data-route="<?= $escaper->escapeHtmlAttr($next->getRoute()) ?>"
            x-bind="buttonNext">
            <span class="group-disabled:invisible pr-3">
                <?= $escaper->escapeHtml(__('Proceed to checkout')) ?>
            </span>
            <svg width="19" height="10" viewBox="0 0 19 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M0.773438 4.91767H17.3381M17.3381 4.91767L13.197 0.776489M17.3381 4.91767L13.197 9.05884" stroke="white" stroke-width="1.55294" stroke-linecap="round" stroke-linejoin="round" />
            </svg>

            <span class="hidden group-disabled:flex absolute inset-0 justify-center items-center p-2">
                <?= $block->getChildHtml('loader') ?>
            </span>
        </button>
        </div>
        <?= $block->getLayout()
            ->createBlock(\Magento\Cms\Block\Block::class)
            ->setBlockId('checkout_trust_payment_block')
            ->toHtml(); ?>
    <?php endif ?>
<?php endif ?>