<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\Image;
use Magento\Framework\Escaper;

/** @var Image $block */
/** @var Escaper $escaper */
?>

<?php
$label = $block->getLabel();
$fallback = $block->getProduct() ? $block->getProduct()->getName() . ' - Teakea' : 'Teakea product image';
$text = $label ?: $fallback;
?>

<img class="photo image <?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
    <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
    <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtmlAttr($value) ?>"
    <?php endforeach; ?>
    src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
    alt="<?= $escaper->escapeHtmlAttr($text) ?>"
    title="<?= $escaper->escapeHtmlAttr($text) ?>" />