<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Customer\Api\Data\AddressInterface;
use Magento\Customer\Api\Data\AddressSearchResultsInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\Magewire\Checkout\AddressView\ShippingDetails\AddressList as Magewire;
use Hyva\Checkout\ViewModel\Checkout\AddressView\AbstractAddressList;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Magewire $magewire */
/** @var AddressSearchResultsInterface $shippingAddressList */
/** @var AddressInterface $address */
/** @var Escaper $escaper */
/** @var AbstractAddressList $addressList */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$addressList = $block->getData('address_list');
$addressListItems = $addressList->getAddressListItems();
$expandable = count($addressListItems) > 2;
?>

<?php if ($addressListItems): ?>
    <div
        <?php if ($expandable): ?>
            x-data="mountainITTeakeaHyvaCheckoutAddressViewAddressListGrid"
        <?php endif; ?>
    >
        <div
            <?php if ($expandable): ?>
                id="address-grid"
                class="address-grid space-y-2 h-96 overflow-hidden mask-overflow data-[expanded=true]:mask-none data-[expanded=true]:h-auto data-[expanded=true]:mb-3"
                style="--tw-mask-size: 8rem; --tw-mask-dir: to bottom; --tw-mask-start: rgb(var(--tw-mask-color));"
                x-bind="details"
            <?php else: ?>
                class="address-grid space-y-2"
            <?php endif; ?>
        >
            <?php foreach ($addressListItems as $address): ?>
                <div
                    class="address-item border-2 rounded-lg"
                    wire:key="address-<?= /* @noEscape */ $address->getId() ?>"
                    x-data="mountainITTeakeaHyvaCheckoutAddressViewAddressListGrid1" data-hyvacsp1="<?= /* @noEscape */ $address->getId() ?? 0 ?>"
                    x-bind:class="mountainITTeakeaHyvaCheckoutAddressViewAddressListGridClass219" data-hyvacsp2="<?= /* @noEscape */ (int) $magewire->activeAddressEntity ?>"
                >
                    <label class="flex gap-x-2.5 mb-0 p-4 cursor-pointer">
                        <input
                            type="radio"
                            wire:model="activeAddressEntity"
                            value="<?=  /* @noEscape */ $address->getId() ?? 0 ?>"
                            name="<?= $escaper->escapeHtmlAttr('address_' . $addressList->getTypeNamespace()) ?>"
                            id="<?= $escaper->escapeHtmlAttr($addressList->renderEntityName($address)) ?>"
                            class="form-radio"
                        />
                        <span class="h-full text-sm">
                            <?= /* @noEscape */ $addressList->renderAddress($address) ?>
                        </span>
                        <?php if (! is_numeric($address->getId())): ?>
                            <div class="toolbar flex gap-x-4">
                                <button
                                    wire:click="$emitTo('<?= /* @noEscape */ $addressList->getModalAddressFormBlockName() ?>', 'edit')"
                                    class="rounded-full w-9 h-9 bg-gray-200 border-0 flex-shrink-0 group-hover:bg-gray-300 group-hover:text-gray-600"
                                    title="<?= $escaper->escapeHtmlAttr(__('Edit Address')) ?>"
                                >
                                    <span class="sr-only"><?= $escaper->escapeHtml(__('Edit Address')) ?></span>
                                    <span class="w-full h-full rounded-full inline-flex items-center justify-center hover:text-green-700">
                                        <?= $heroicons->pencilAltHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
                                    </span>
                                </button>
                            </div>
                        <?php endif ?>
                    </label>
                </div>
            <?php endforeach ?>
        </div>
        <?php if ($expandable): ?>
            <button
                class="btn btn-secondary justify-center w-full"
                aria-controls="address-grid"
                x-bind="toggle"
            ><?= $escaper->escapeHtml(__('Show all')) ?></button>
        <?php endif; ?>
    </div>
<?php endif ?>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function mountainITTeakeaHyvaCheckoutAddressViewAddressListGrid() {
    return Object.assign(
        hyvaExpandSavedAddress.call(this)
        ,{
            ['mountainITTeakeaHyvaCheckoutAddressViewAddressListGridClass219']() {return ( this.id === parseInt(this.$el.dataset.hyvacsp2))  ? 'active bg-primary bg-opacity-10 border-primary' : 'inactive bg-white'},
        }
    )
}
window.addEventListener('alpine:init', () => Alpine.data('mountainITTeakeaHyvaCheckoutAddressViewAddressListGrid', mountainITTeakeaHyvaCheckoutAddressViewAddressListGrid), {once: true});
function mountainITTeakeaHyvaCheckoutAddressViewAddressListGrid1() {
    return Object.assign(
        Object.assign({ id: this.$el.dataset.hyvacsp1 }, mountainITTeakeaHyvaCheckoutAddressViewAddressListGrid())
    )
}
window.addEventListener('alpine:init', () => Alpine.data('mountainITTeakeaHyvaCheckoutAddressViewAddressListGrid1', mountainITTeakeaHyvaCheckoutAddressViewAddressListGrid1), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>