<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityFieldInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var EntityFieldInterface $field */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$element = $block->getData('element');
?>
<?php if ($element): ?>
    <div
        x-data="TechticHyvaChildHyvaFormFieldHtmlTooltip"
        class="relative tooltip flex">
        <button
            type="button"
            x-on:mouseenter.self="TechticHyvaChildHyvaFormFieldHtmlTooltipMouseenterSelf243"
            x-on:mouseleave.self="TechticHyvaChildHyvaFormFieldHtmlTooltipMouseleaveSelf244"
            x-on:click="TechticHyvaChildHyvaFormFieldHtmlTooltipClick245"
            x-on:touchstart.prevent="TechticHyvaChildHyvaFormFieldHtmlTooltipTouchstartPrevent246"
            x-on:click.outside="TechticHyvaChildHyvaFormFieldHtmlTooltipClickOutside247"
            class="align-middle hover:cursor-pointer opacity-75 hover:opacity-100 focus:outline-none hover:bg-transparent focus:bg-transparent"
            aria-label="<?= $escaper->escapeHtmlAttr(__('More information')) ?>"
            aria-describedby="form-tooltip-<?= $escaper->escapeHtmlAttr($element->getId()) ?>">

            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path d="M11.967 12.75C12.967 11.75 13.967 11.3546 13.967 10.25C13.967 9.14543 13.0716 8.25 11.967 8.25C11.0351 8.25 10.252 8.88739 10.03 9.75M11.967 15.75H11.977M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" stroke="black" stroke-linecap="round" />
            </svg>
        </button>
        <div
            id="form-tooltip-<?= $escaper->escapeHtmlAttr($element->getId()) ?>"
            role="tooltip"
            class="absolute top-full right-0 lg:left-0 w-80 mt-3 px-3 py-2 bg-gray-500 text-white shadow-lg rounded-md z-50"
            x-show="tooltipVisible"
            x-cloak>
            <div id="tooltip-content" class="absolute right-2 lg:left-2 -top-3 h-3 w-3 bg-inherit rotate-45 transform origin-bottom-left"></div>
            <?= $escaper->escapeHtml(__($element->getTooltip())) ?>
        </div>
    </div>
<?php endif ?>