<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;

/** @var ViewModelRegistry $viewModels */
$hyvaCsp = $viewModels->require(\Hyva\Theme\ViewModel\HyvaCsp::class);
?>
<script>
    <?php /** Generated with hyva-csp-helper.php */ ?>

    function TechticHyvaChildHyvaFormFieldHtmlTooltip() {
        return Object.assign({
            tooltipVisible: false
        }, {
            ['TechticHyvaChildHyvaFormFieldHtmlTooltipClick245'](event) {
                return this.tooltipVisible = !this.tooltipVisible
            },
            ['TechticHyvaChildHyvaFormFieldHtmlTooltipClickOutside247'](event) {
                return this.tooltipVisible = false
            },
            ['TechticHyvaChildHyvaFormFieldHtmlTooltipMouseenterSelf243'](event) {
                return this.tooltipVisible = true
            },
            ['TechticHyvaChildHyvaFormFieldHtmlTooltipMouseleaveSelf244'](event) {
                return this.tooltipVisible = false
            },
            ['TechticHyvaChildHyvaFormFieldHtmlTooltipTouchstartPrevent246'](event) {
                return this.tooltipVisible = true
            },
        })
    }
    window.addEventListener('alpine:init', () => Alpine.data('TechticHyvaChildHyvaFormFieldHtmlTooltip', TechticHyvaChildHyvaFormFieldHtmlTooltip), {
        once: true
    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>