<?php

use Magento\Theme\Block\Html\Footer;
/** @var Footer $block */
?>

<div class="w-full bg-[#FFF9F3] border-t border-teakea-light-gray">
    <div class="max-w-screen-xl mx-auto px-4 py-6 text-center">

        <div class="flex justify-center gap-7 text-sm text-teakea-gray text-normal">
            <a href="/retourneren-en-terugbetalingen" class="">
                <?= $escaper->escapeHtml(__('Returns & Refunds')) ?>
            </a>
            <a href="/privacybeleid" class="">
                <?= $escaper->escapeHtml(__('Privacy Policy')) ?>
            </a>
        </div>

        <div class="mt-4 text-sm text-normal text-teakea-neutral">
            <?= $escaper->escapeHtml($block->getCopyright()) ?>
        </div>

    </div>
</div>
