<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Customer "Remember Me" template
 */

/** @var \Magento\Persistent\Block\Form\Remember $block */

?>
<div id="remember-me-box" class="field choice persistent mt-0 text-sm">
    <?php $rememberMeId = 'remember_me' . $block->getRandomString(10); ?>
    <input type="checkbox" name="persistent_remember_me" class="checkbox w-4 h-4 rounded border-techtic-light-gray text-[#163A20] focus:outline-none focus:ring-2 focus:ring-[#163A20]/30 focus:border-[#163A20]" id="<?= $block->escapeHtmlAttr($rememberMeId) ?>" <?php if ($block->isRememberMeChecked()) : ?> checked="checked" <?php endif; ?> title="<?= $block->escapeHtmlAttr(__('Remember Me')) ?>" />
    <label for="<?= $block->escapeHtmlAttr($rememberMeId) ?>" class="label"><span><?= $block->escapeHtml(__('Stay logged in')) ?></span></label>
</div>