<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Contact\Block\ContactForm;
use Magento\Contact\Helper\Data as ContactHelper;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\ReCaptcha;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var ContactForm $block */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha|null */

$formId = 'contact';
/** @var ContactHelper $contactHelper */
$contactHelper = $this->helper(ContactHelper::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that would break the dependency
// on the Magento_ReCaptchaContact module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<div class="max-w-[650px]">
    <form class="form contact w-full"
        action="<?= $escaper->escapeUrl($block->getFormAction()) ?>"
        id="<?= $escaper->escapeHtmlAttr($formId) ?>"
        method="post"
        x-data="initContactForm()"
        @submit.prevent="submitForm()">
        <fieldset class="">
            <div class="flex flex-col text-left w-full mb-7">
                <h2 class="text-2xl lg:text-3xl font-medium mb-2.5 text-black">
                    <span><?= $escaper->escapeHtml(__('Get in touch')) ?></span>
                </h2>
                <p class="text-base"><?= $escaper->escapeHtml(__('Do you have a question or need advice? Fill in your details below and we’ll respond within 24 hours.')) ?></p>
            </div>
            <div class="flex flex-wrap -m-2">
                <div class="field name required p-2 w-1/2 text-left">
                    <label
                        class="label text-black font-medium text-base"
                        for="name">
                        <span><?= $escaper->escapeHtml(__('Name')) ?></span>
                    </label>
                    <input
                        name="name"
                        id="name"
                        required
                        title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                        value="<?= $escaper->escapeHtmlAttr($contactHelper->getPostValue('name') ?: $contactHelper->getUserName()) ?>"
                        class="input w-full mt-2.5 mr-0 bg-transparent border border-techtic-light-gray rounded-lg"
                        type="text" />
                </div>
                <div class="field telephone p-2 w-1/2 text-left">
                    <label
                        class="label text-black font-medium text-base"
                        for="telephone">
                        <span><?= $escaper->escapeHtml(__('Phone number (optional)')) ?></span>
                    </label>
                    <input
                        name="telephone"
                        id="telephone"
                        type="tel"
                        inputmode="tel"
                        autocomplete="tel-national"
                        title="<?= $escaper->escapeHtmlAttr(__('Phone number')) ?>"
                        value="<?= $escaper->escapeHtmlAttr($contactHelper->getPostValue('telephone')) ?>"
                        class="input w-full mt-2.5 mr-0 bg-transparent border border-techtic-light-gray rounded-lg" />
                </div>
                <div class="field email required p-2 w-full text-left">
                    <label
                        class="label text-black font-medium text-base"
                        for="email">
                        <span><?= $escaper->escapeHtml(__('E-mail')) ?></span>
                    </label>
                    <input
                        name="email"
                        id="email"
                        type="email"
                        inputmode="email"
                        autocomplete="email"
                        required
                        title="<?= $escaper->escapeHtmlAttr(__('E-mail')) ?>"
                        value="<?= $escaper->escapeHtmlAttr(
                                    $contactHelper->getPostValue('email') ?: $contactHelper->getUserEmail()
                                ) ?>"
                        class="input w-full mt-2.5 mr-0 bg-transparent border border-techtic-light-gray rounded-lg" />
                </div>
                <div class="field comment required pt-2 px-2 w-full text-left">
                    <label
                        class="label text-black font-medium text-base"
                        for="comment"><span><?= $escaper->escapeHtml(__('Your question or message')) ?></span>
                    </label>
                    <textarea
                        name="comment"
                        id="comment"
                        required
                        title="<?= $escaper->escapeHtmlAttr(__('Your question or message')) ?>"
                        class="input w-full mt-2.5 mr-0 p-0 bg-transparent border border-techtic-light-gray rounded-lg"
                        cols="5"
                        rows="3">
                        <?= $escaper->escapeHtml($contactHelper->getPostValue('comment')) ?>
                    </textarea>
                </div>
                <?= $block->getChildHtml('form.additional.info') ?>
                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>
            </div>
        </fieldset>
        <div class="w-full mt-7">
            <?= $block->getBlockHtml('formkey') ?>
            <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Send message')) ?>" class="bg-techtic-terracotta px-16 rounded-lg h-12">
                <span class="text-white text-sm font-semibold leading-5 uppercase whitespace-nowrap"><?= $escaper->escapeHtml(__('Send message')) ?></span>
            </button>
        </div>
        <div class="w-full">
            <?= $block->getChildHtml('form.additional.after') ?>
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>
        </div>
    </form>
    <script>
        function initContactForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
    <div class="card lg:w-1/2 md:w-1/3 hidden">
        <?= $block->getChildHtml('contact.details') ?>
    </div>
</div>