<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div class="toolbar-sorter sorter flex items-center order-1 col-span-3 sm:col-span-6
        md:col-span-3 lg:col-span-6 justify-end gap-2.5 md:pt-0 pt-5">
    <label class="text-sm uppercase flex w-max">Sorteer op :</label>
    <label class="inline-block">
        <select data-role="sorter"
            class="form-select sorter-options min-h-[40px] py-0 border rounded-[50px] border-[#0000001A] pr-6 pl-4 text-sm uppercase !w-fit min-w-[140px]"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Sort By')) ?>"
            @change="changeUrl(
                    'product_list_order',
                    $event.currentTarget.options[$event.currentTarget.selectedIndex].value,
                    options.orderDefault
                )">
            <?php foreach ($block->getAvailableOrders() as $orderCode => $orderLabel): ?>
                <option class="uppercase" value="<?= $escaper->escapeHtmlAttr($orderCode) ?>"
                    <?php if ($block->isOrderCurrent($orderCode)): ?>
                    selected="selected"
                    <?php endif; ?>>
                    <?= $escaper->escapeHtml(__($orderLabel)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </label>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <!-- <a title="<?= $escaper->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           @click.prevent="changeUrl('product_list_dir', 'asc', options.directionDefault)"
        >
            <?= $heroicons->sortAscendingHtml(); ?>
        </a> -->
    <?php else: ?>
        <!-- <a title="<?= $escaper->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           @click.prevent="changeUrl('product_list_dir', 'desc', options.directionDefault)"
        >
            <?= $heroicons->sortDescendingHtml(); ?>
        </a> -->
    <?php endif; ?>
</div>