<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="flex flex-col h-full items-center justify-center text-center text-xl space-y-5 mt-36">
    <p class="text-2xl">
        <?= $escaper->escapeHtml(__('Order process completed successfully.')) ?>
    </p>

    <p>
        <?= $escaper->escapeHtml(__('You are being redirected, please wait...')) ?>
    </p>
</div>
