<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CustomOption;
use Magento\Catalog\Block\Product\View\Options\Type\Select;
use Magento\Framework\Escaper;

/** @var Select $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$option = $block->getOption();
$product = $block->getProduct();

/** @var CustomOption $customOptionsViewModel */
$customOptionsViewModel = $viewModels->require(CustomOption::class);

?>
<div class="flex flex-col w-full items-center gap-y-2.5">
    <label class="label text-left w-full text-black text-lg font-semibold pr-1.5 capitalize"
        for="select_<?= $escaper->escapeHtmlAttr($option->getId()) ?>">
        <span><?= $escaper->escapeHtml($option->getTitle()) . ":" ?></span>
        <?php if ($option->getIsRequire()): ?>
            <span class="sup text-sm absolute">*</span>
        <?php endif; ?>
    </label>
    <div class="!text-[#646464] text-left w-full rounded-lg">
        <?= $customOptionsViewModel->getOptionHtml($option, $product); ?>
    </div>
</div>