<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPrice;
use Magento\Catalog\Api\Data\ProductCustomOptionInterface;
use Magento\Catalog\Block\Product\View\Options\Type\Text;
use Magento\Catalog\Model\Product\Option;
use Magento\Catalog\Pricing\Price\CustomOptionPrice;
use Magento\Framework\Escaper;

/** @var Text $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$product = $block->getProduct();

/** @var Option $option */
$option = $block->getOption();
$optionId = $option->getId();
/** @var ProductPrice $productPriceViewModel */
$productPriceViewModel = $viewModels->require(ProductPrice::class);
$optionPrice = $productPriceViewModel->getCustomOptionPrice($option, CustomOptionPrice::PRICE_CODE, $product);
if ($productPriceViewModel->displayPriceInclAndExclTax()) {
    $optionBasePrice = $productPriceViewModel->getCustomOptionPriceExclTax($option, CustomOptionPrice::PRICE_CODE, $product);
}
?>

<div class="flex flex-col w-full items-center gap-y-2.5">
    <div class="flex flex-col w-full">
        <label class="text-black text-lg font-semibold"><?= $escaper->escapeHtml(__('Own color?')) ?></label>
        <label class="label text-sm !text-[#646464] text-left font-medium mt-1 capitalize"
            for="options_<?= $escaper->escapeHtmlAttr($optionId) ?>_text"
            x-html="updateOptionPrice('<?= $escaper->escapeJs($optionId) ?>', $el)">
            <span><?= $escaper->escapeHtml($option->getTitle()) ?></span>
            <?php if ($option->getIsRequire()): ?>
                <span class="sup text-sm">*</span>
            <?php endif; ?>
            <span><?= /* @noEscape */ $block->getFormattedPrice() ?></span>
        </label>
    </div>

    <div class="text-[#646464] text-left w-full">
        <?php if ($option->getType() == ProductCustomOptionInterface::OPTION_TYPE_FIELD): ?>
            <input type="text"
                id="options_<?= $escaper->escapeHtmlAttr($optionId) ?>_text"
                class="product-custom-option form-input w-full bg-transparent border-[#D8D8D8] text-[#646464] text-base rounded-lg py-3 placeholder:text-[#646464]"
                name="options[<?= $escaper->escapeHtmlAttr($optionId) ?>]"
                value="<?= $escaper->escapeHtml($block->getDefaultValue()) ?>"
                placeholder="<?= $escaper->escapeHtml(__('Typ hier ')) ?><?php if ($option->getMaxCharacters()): ?><?= $escaper->escapeHtml(__('(Maximum %1 characters)', $option->getMaxCharacters())) ?><?php endif; ?>"
                <?php if ($option->getMaxCharacters()): ?>
                maxlength="<?= (int)$option->getMaxCharacters() ?>"
                <?php endif; ?>
                <?= $option->getIsRequire() ? 'required' : '' ?>
                data-price-amount="<?= $escaper->escapeHtmlAttr($optionPrice) ?>"
                data-price-type="<?= $escaper->escapeHtmlAttr($option->getPriceType()) ?>"
                data-option-id="<?= $escaper->escapeHtmlAttr($optionId) ?>"
                x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>"
                x-on:input="updateCustomOptionValue(
                        $dispatch,
                        '<?= $escaper->escapeHtmlAttr($optionId) ?>',
                        $event.target
                   )" />
        <?php elseif ($option->getType() == ProductCustomOptionInterface::OPTION_TYPE_AREA): ?>
            <textarea id="options_<?= $escaper->escapeHtmlAttr($optionId) ?>_text"
                class="product-custom-option form-textarea w-full rounded-lg placeholder:text-[#646464]"
                placeholder="<?= $escaper->escapeHtml(__('Typ hier ')) ?><?php if ($option->getMaxCharacters()): ?><?= $escaper->escapeHtml(__('(Maximum %1 characters)', $option->getMaxCharacters())) ?><?php endif; ?>"
                <?php if ($option->getMaxCharacters()): ?>
                maxlength="<?= (int)$option->getMaxCharacters() ?>"
                <?php endif; ?>
                <?= $option->getIsRequire() ? 'required' : '' ?>
                name="options[<?= $escaper->escapeHtmlAttr($optionId) ?>]"
                rows="5"
                cols="25"
                data-price-amount="<?= $escaper->escapeHtmlAttr($optionPrice) ?>"
                data-price-type="<?= $escaper->escapeHtmlAttr($option->getPriceType()) ?>"
                data-option-id="<?= $escaper->escapeHtmlAttr($optionId) ?>"
                x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>"
                x-on:input="updateCustomOptionValue(
                        $dispatch,
                        '<?= $escaper->escapeHtmlAttr($optionId) ?>',
                        $event.target
                   )"><?= $escaper->escapeHtml($block->getDefaultValue()) ?></textarea>
        <?php endif; ?>
    </div>
</div>