<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var FormatterViewModel $formatterViewModel */

$formatterViewModel = $viewModels->require(FormatterViewModel::class);

$quoteItem = $block->getData('quote_item');
$options = $quoteItem['options'] ?? null;
?>
<?php if ($options): ?>
    <table class="table-auto space-y-1 text-xs bg-teak-stone-light border border-[#F0F0F0] p-2.5 max-w-max">
        <tbody>
            <?php foreach ($options as $option): ?>
                <tr>
                    <td class="font-normal py-2 text-teakea-gray w-3/4 pl-2">
                        <?= $escaper->escapeHtml(__($option['label'])) ?>
                    </td>

                    <td class="font-medium pl-8 lg:pl-3 text-slate-950 py-2 pr-2">
                        <?= /* @noEscape */ __($option['value']) ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>