<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\MethodMetaDataInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Checkout\ViewModel\Checkout\Payment\MethodList as ViewModel;
use Hyva\Checkout\Magewire\Checkout\Payment\MethodList as Magewire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Quote\Api\Data\PaymentMethodInterface;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var ViewModel $viewModel */
/** @var PaymentMethodInterface $method */
/** @var Magewire $magewire */
/** @var Escaper $escaper */
/** @var MethodMetaDataInterface $methodMetaData */

$viewModel = $viewModels->require(ViewModel::class);
$methods = $viewModel->getList();
?>
<div id="payment-methods" class="pt-1">
    <?php if ($methods): ?>
        <script>
            window.addEventListener('checkout:step:loaded', () => {
                if ('<?= $escaper->escapeJs($magewire->method) ?>' && document.getElementById('payment-method-list')) {
                    window.dispatchEvent(new CustomEvent('checkout:payment:method-activate', {
                        detail: {
                            method: '<?= $escaper->escapeJs($magewire->method) ?>'
                        }
                    }))
                }
            }, {
                once: true
            })
        </script>
        <?php $hyvaCsp->registerInlineScript() ?>

        <div id="payment-method-list" class="md:space-y-5 space-y-2.5">
            <?php foreach ($methods as $method): ?>
                <?php $methodCodeAttr = $escaper->escapeHtmlAttr($method->getCode()) ?>
                <?php $methodMetaData = $viewModel->getMethodMetaData($block, $method) ?>

                <div
                    id="payment-method-option-<?= /* @noEscape */ $methodCodeAttr ?>"
                    class="rounded-lg px-4 py-2 text-sm <?= $magewire->method === $method->getCode() ? 'active bg-teakea-red bg-opacity-10 border-teakea-red border' : 'inactive bg-teakea-lighter-gray' ?>"
                    wire:key="<?= /* @noEscape */ $methodCodeAttr ?>">
                    <label class="flex items-center gap-x-2 cursor-pointer text-teakea-gray text-sm font-normal rounded-lg <?php $magewire->method === $method->getCode() ? 'active bg-teakea-red bg-opacity-10' : 'inactive bg-teakea-lighter-gray' ?>">
                        <input
                            type="radio"
                            class="form-radio border-[#C7C7C7] bg-teakea-lighter-gray"
                            id="payment-method-<?= /* @noEscape */ $methodCodeAttr ?>"
                            name="payment-method-option"
                            value="<?= /* @noEscape */ $methodCodeAttr ?>"
                            wire:model="method" />

                        <span class="flex justify-between items-center space-x-4 w-full">
                            <span class="text-black font-normal flex flex-col break-words hyphens-auto leading-relaxed">
                                <?= $escaper->escapeHtml($method->getTitle()) ?>

                                <?php if ($methodMetaData->hasSubTitle()): ?>
                                    <span class="text-gray-700 font-normal break-words hyphens-auto">
                                        <?= $escaper->escapeHtml($methodMetaData->getSubTitle()) ?>
                                    </span>
                                <?php endif ?>
                            </span>

                            <?php if ($methodMetaData->canRenderIcon() && $iconHtml = $methodMetaData->renderIcon()): ?>
                                <div>
                                    <?= /* @noEscape */ $iconHtml; ?>
                                </div>
                            <?php endif ?>
                        </span>
                    </label>
                    <?php if ($viewModel->canShowMethod($block, $method, $magewire->method)): ?>
                        <?php $html = $viewModel->getMethodBlock($block, $method)->toHtml() ?>

                        <?php if (! empty($html)): ?>
                            <div id="<?= 'payment-method-view-' . /* @noEscape */ $methodCodeAttr ?>">
                                <?= /* @noEscape */ $html ?>
                            </div>
                        <?php endif ?>
                    <?php endif ?>
                </div>
            <?php endforeach ?>
        </div>
    <?php else: ?>
        <div class="message warning">
            <?= $escaper->escapeHtml(__('No Payment method available.')) ?>
        </div>
    <?php endif ?>
</div>